/* tslint:disable */
/* eslint-disable */
/**
 * TMDB API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { AccountGetFavorites200ResponseResultsInner } from './AccountGetFavorites200ResponseResultsInner';
import {
    AccountGetFavorites200ResponseResultsInnerFromJSON,
    AccountGetFavorites200ResponseResultsInnerFromJSONTyped,
    AccountGetFavorites200ResponseResultsInnerToJSON,
} from './AccountGetFavorites200ResponseResultsInner';

/**
 * 
 * @export
 * @interface AccountGetFavorites200Response
 */
export interface AccountGetFavorites200Response {
    /**
     * 
     * @type {number}
     * @memberof AccountGetFavorites200Response
     */
    page?: number;
    /**
     * 
     * @type {Array<AccountGetFavorites200ResponseResultsInner>}
     * @memberof AccountGetFavorites200Response
     */
    results?: Array<AccountGetFavorites200ResponseResultsInner>;
    /**
     * 
     * @type {number}
     * @memberof AccountGetFavorites200Response
     */
    total_pages?: number;
    /**
     * 
     * @type {number}
     * @memberof AccountGetFavorites200Response
     */
    total_results?: number;
}

/**
 * Check if a given object implements the AccountGetFavorites200Response interface.
 */
export function instanceOfAccountGetFavorites200Response(value: object): value is AccountGetFavorites200Response {
    return true;
}

export function AccountGetFavorites200ResponseFromJSON(json: any): AccountGetFavorites200Response {
    return AccountGetFavorites200ResponseFromJSONTyped(json, false);
}

export function AccountGetFavorites200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): AccountGetFavorites200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'page': json['page'] == null ? undefined : json['page'],
        'results': json['results'] == null ? undefined : ((json['results'] as Array<any>).map(AccountGetFavorites200ResponseResultsInnerFromJSON)),
        'total_pages': json['total_pages'] == null ? undefined : json['total_pages'],
        'total_results': json['total_results'] == null ? undefined : json['total_results'],
    };
}

export function AccountGetFavorites200ResponseToJSON(value?: AccountGetFavorites200Response | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'page': value['page'],
        'results': value['results'] == null ? undefined : ((value['results'] as Array<any>).map(AccountGetFavorites200ResponseResultsInnerToJSON)),
        'total_pages': value['total_pages'],
        'total_results': value['total_results'],
    };
}

