/* tslint:disable */
/* eslint-disable */
/**
 * TMDB API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { AccountDetails200ResponseAvatar } from './AccountDetails200ResponseAvatar';
import {
    AccountDetails200ResponseAvatarFromJSON,
    AccountDetails200ResponseAvatarFromJSONTyped,
    AccountDetails200ResponseAvatarToJSON,
} from './AccountDetails200ResponseAvatar';

/**
 * 
 * @export
 * @interface AccountDetails200Response
 */
export interface AccountDetails200Response {
    /**
     * 
     * @type {AccountDetails200ResponseAvatar}
     * @memberof AccountDetails200Response
     */
    avatar?: AccountDetails200ResponseAvatar;
    /**
     * 
     * @type {number}
     * @memberof AccountDetails200Response
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof AccountDetails200Response
     */
    iso_639_1?: string;
    /**
     * 
     * @type {string}
     * @memberof AccountDetails200Response
     */
    iso_3166_1?: string;
    /**
     * 
     * @type {string}
     * @memberof AccountDetails200Response
     */
    name?: string;
    /**
     * 
     * @type {boolean}
     * @memberof AccountDetails200Response
     */
    include_adult?: boolean;
    /**
     * 
     * @type {string}
     * @memberof AccountDetails200Response
     */
    username?: string;
}

/**
 * Check if a given object implements the AccountDetails200Response interface.
 */
export function instanceOfAccountDetails200Response(value: object): value is AccountDetails200Response {
    return true;
}

export function AccountDetails200ResponseFromJSON(json: any): AccountDetails200Response {
    return AccountDetails200ResponseFromJSONTyped(json, false);
}

export function AccountDetails200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): AccountDetails200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'avatar': json['avatar'] == null ? undefined : AccountDetails200ResponseAvatarFromJSON(json['avatar']),
        'id': json['id'] == null ? undefined : json['id'],
        'iso_639_1': json['iso_639_1'] == null ? undefined : json['iso_639_1'],
        'iso_3166_1': json['iso_3166_1'] == null ? undefined : json['iso_3166_1'],
        'name': json['name'] == null ? undefined : json['name'],
        'include_adult': json['include_adult'] == null ? undefined : json['include_adult'],
        'username': json['username'] == null ? undefined : json['username'],
    };
}

export function AccountDetails200ResponseToJSON(value?: AccountDetails200Response | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'avatar': AccountDetails200ResponseAvatarToJSON(value['avatar']),
        'id': value['id'],
        'iso_639_1': value['iso_639_1'],
        'iso_3166_1': value['iso_3166_1'],
        'name': value['name'],
        'include_adult': value['include_adult'],
        'username': value['username'],
    };
}

