/* tslint:disable */
/* eslint-disable */
/**
 * TMDB API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { AccountRatedTv200ResponseResultsInner } from './AccountRatedTv200ResponseResultsInner';
import {
    AccountRatedTv200ResponseResultsInnerFromJSON,
    AccountRatedTv200ResponseResultsInnerFromJSONTyped,
    AccountRatedTv200ResponseResultsInnerToJSON,
} from './AccountRatedTv200ResponseResultsInner';

/**
 * 
 * @export
 * @interface AccountRatedTv200Response
 */
export interface AccountRatedTv200Response {
    /**
     * 
     * @type {number}
     * @memberof AccountRatedTv200Response
     */
    page?: number;
    /**
     * 
     * @type {Array<AccountRatedTv200ResponseResultsInner>}
     * @memberof AccountRatedTv200Response
     */
    results?: Array<AccountRatedTv200ResponseResultsInner>;
    /**
     * 
     * @type {number}
     * @memberof AccountRatedTv200Response
     */
    total_pages?: number;
    /**
     * 
     * @type {number}
     * @memberof AccountRatedTv200Response
     */
    total_results?: number;
}

/**
 * Check if a given object implements the AccountRatedTv200Response interface.
 */
export function instanceOfAccountRatedTv200Response(value: object): value is AccountRatedTv200Response {
    return true;
}

export function AccountRatedTv200ResponseFromJSON(json: any): AccountRatedTv200Response {
    return AccountRatedTv200ResponseFromJSONTyped(json, false);
}

export function AccountRatedTv200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): AccountRatedTv200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'page': json['page'] == null ? undefined : json['page'],
        'results': json['results'] == null ? undefined : ((json['results'] as Array<any>).map(AccountRatedTv200ResponseResultsInnerFromJSON)),
        'total_pages': json['total_pages'] == null ? undefined : json['total_pages'],
        'total_results': json['total_results'] == null ? undefined : json['total_results'],
    };
}

export function AccountRatedTv200ResponseToJSON(value?: AccountRatedTv200Response | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'page': value['page'],
        'results': value['results'] == null ? undefined : ((value['results'] as Array<any>).map(AccountRatedTv200ResponseResultsInnerToJSON)),
        'total_pages': value['total_pages'],
        'total_results': value['total_results'],
    };
}

