/* tslint:disable */
/* eslint-disable */
/**
 * TMDB API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AlternativeNamesCopy200ResponseLogosInner
 */
export interface AlternativeNamesCopy200ResponseLogosInner {
    /**
     * 
     * @type {number}
     * @memberof AlternativeNamesCopy200ResponseLogosInner
     */
    aspect_ratio?: number;
    /**
     * 
     * @type {string}
     * @memberof AlternativeNamesCopy200ResponseLogosInner
     */
    file_path?: string;
    /**
     * 
     * @type {number}
     * @memberof AlternativeNamesCopy200ResponseLogosInner
     */
    height?: number;
    /**
     * 
     * @type {string}
     * @memberof AlternativeNamesCopy200ResponseLogosInner
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof AlternativeNamesCopy200ResponseLogosInner
     */
    file_type?: string;
    /**
     * 
     * @type {number}
     * @memberof AlternativeNamesCopy200ResponseLogosInner
     */
    vote_average?: number;
    /**
     * 
     * @type {number}
     * @memberof AlternativeNamesCopy200ResponseLogosInner
     */
    vote_count?: number;
    /**
     * 
     * @type {number}
     * @memberof AlternativeNamesCopy200ResponseLogosInner
     */
    width?: number;
}

/**
 * Check if a given object implements the AlternativeNamesCopy200ResponseLogosInner interface.
 */
export function instanceOfAlternativeNamesCopy200ResponseLogosInner(value: object): value is AlternativeNamesCopy200ResponseLogosInner {
    return true;
}

export function AlternativeNamesCopy200ResponseLogosInnerFromJSON(json: any): AlternativeNamesCopy200ResponseLogosInner {
    return AlternativeNamesCopy200ResponseLogosInnerFromJSONTyped(json, false);
}

export function AlternativeNamesCopy200ResponseLogosInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): AlternativeNamesCopy200ResponseLogosInner {
    if (json == null) {
        return json;
    }
    return {
        
        'aspect_ratio': json['aspect_ratio'] == null ? undefined : json['aspect_ratio'],
        'file_path': json['file_path'] == null ? undefined : json['file_path'],
        'height': json['height'] == null ? undefined : json['height'],
        'id': json['id'] == null ? undefined : json['id'],
        'file_type': json['file_type'] == null ? undefined : json['file_type'],
        'vote_average': json['vote_average'] == null ? undefined : json['vote_average'],
        'vote_count': json['vote_count'] == null ? undefined : json['vote_count'],
        'width': json['width'] == null ? undefined : json['width'],
    };
}

export function AlternativeNamesCopy200ResponseLogosInnerToJSON(value?: AlternativeNamesCopy200ResponseLogosInner | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'aspect_ratio': value['aspect_ratio'],
        'file_path': value['file_path'],
        'height': value['height'],
        'id': value['id'],
        'file_type': value['file_type'],
        'vote_average': value['vote_average'],
        'vote_count': value['vote_count'],
        'width': value['width'],
    };
}

