/* tslint:disable */
/* eslint-disable */
/**
 * TMDB API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AuthenticationValidateKey401Response
 */
export interface AuthenticationValidateKey401Response {
    /**
     * 
     * @type {number}
     * @memberof AuthenticationValidateKey401Response
     */
    status_code?: number;
    /**
     * 
     * @type {string}
     * @memberof AuthenticationValidateKey401Response
     */
    status_message?: string;
    /**
     * 
     * @type {boolean}
     * @memberof AuthenticationValidateKey401Response
     */
    success?: boolean;
}

/**
 * Check if a given object implements the AuthenticationValidateKey401Response interface.
 */
export function instanceOfAuthenticationValidateKey401Response(value: object): value is AuthenticationValidateKey401Response {
    return true;
}

export function AuthenticationValidateKey401ResponseFromJSON(json: any): AuthenticationValidateKey401Response {
    return AuthenticationValidateKey401ResponseFromJSONTyped(json, false);
}

export function AuthenticationValidateKey401ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): AuthenticationValidateKey401Response {
    if (json == null) {
        return json;
    }
    return {
        
        'status_code': json['status_code'] == null ? undefined : json['status_code'],
        'status_message': json['status_message'] == null ? undefined : json['status_message'],
        'success': json['success'] == null ? undefined : json['success'],
    };
}

export function AuthenticationValidateKey401ResponseToJSON(value?: AuthenticationValidateKey401Response | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'status_code': value['status_code'],
        'status_message': value['status_message'],
        'success': value['success'],
    };
}

