/* tslint:disable */
/* eslint-disable */
/**
 * TMDB API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { CertificationsTvList200ResponseCertificationsITInner } from './CertificationsTvList200ResponseCertificationsITInner';
import {
    CertificationsTvList200ResponseCertificationsITInnerFromJSON,
    CertificationsTvList200ResponseCertificationsITInnerFromJSONTyped,
    CertificationsTvList200ResponseCertificationsITInnerToJSON,
} from './CertificationsTvList200ResponseCertificationsITInner';
import type { CertificationsTvList200ResponseCertificationsDKInner } from './CertificationsTvList200ResponseCertificationsDKInner';
import {
    CertificationsTvList200ResponseCertificationsDKInnerFromJSON,
    CertificationsTvList200ResponseCertificationsDKInnerFromJSONTyped,
    CertificationsTvList200ResponseCertificationsDKInnerToJSON,
} from './CertificationsTvList200ResponseCertificationsDKInner';
import type { CertificationsTvList200ResponseCertificationsINInner } from './CertificationsTvList200ResponseCertificationsINInner';
import {
    CertificationsTvList200ResponseCertificationsINInnerFromJSON,
    CertificationsTvList200ResponseCertificationsINInnerFromJSONTyped,
    CertificationsTvList200ResponseCertificationsINInnerToJSON,
} from './CertificationsTvList200ResponseCertificationsINInner';
import type { CertificationsTvList200ResponseCertificationsNZInner } from './CertificationsTvList200ResponseCertificationsNZInner';
import {
    CertificationsTvList200ResponseCertificationsNZInnerFromJSON,
    CertificationsTvList200ResponseCertificationsNZInnerFromJSONTyped,
    CertificationsTvList200ResponseCertificationsNZInnerToJSON,
} from './CertificationsTvList200ResponseCertificationsNZInner';
import type { CertificationsTvList200ResponseCertificationsDEInner } from './CertificationsTvList200ResponseCertificationsDEInner';
import {
    CertificationsTvList200ResponseCertificationsDEInnerFromJSON,
    CertificationsTvList200ResponseCertificationsDEInnerFromJSONTyped,
    CertificationsTvList200ResponseCertificationsDEInnerToJSON,
} from './CertificationsTvList200ResponseCertificationsDEInner';
import type { CertificationMovieList200ResponseCertificationsPRInner } from './CertificationMovieList200ResponseCertificationsPRInner';
import {
    CertificationMovieList200ResponseCertificationsPRInnerFromJSON,
    CertificationMovieList200ResponseCertificationsPRInnerFromJSONTyped,
    CertificationMovieList200ResponseCertificationsPRInnerToJSON,
} from './CertificationMovieList200ResponseCertificationsPRInner';
import type { CertificationsTvList200ResponseCertificationsMAInner } from './CertificationsTvList200ResponseCertificationsMAInner';
import {
    CertificationsTvList200ResponseCertificationsMAInnerFromJSON,
    CertificationsTvList200ResponseCertificationsMAInnerFromJSONTyped,
    CertificationsTvList200ResponseCertificationsMAInnerToJSON,
} from './CertificationsTvList200ResponseCertificationsMAInner';
import type { CertificationsTvList200ResponseCertificationsCAInner } from './CertificationsTvList200ResponseCertificationsCAInner';
import {
    CertificationsTvList200ResponseCertificationsCAInnerFromJSON,
    CertificationsTvList200ResponseCertificationsCAInnerFromJSONTyped,
    CertificationsTvList200ResponseCertificationsCAInnerToJSON,
} from './CertificationsTvList200ResponseCertificationsCAInner';
import type { CertificationsTvList200ResponseCertificationsMYInner } from './CertificationsTvList200ResponseCertificationsMYInner';
import {
    CertificationsTvList200ResponseCertificationsMYInnerFromJSON,
    CertificationsTvList200ResponseCertificationsMYInnerFromJSONTyped,
    CertificationsTvList200ResponseCertificationsMYInnerToJSON,
} from './CertificationsTvList200ResponseCertificationsMYInner';
import type { CertificationsTvList200ResponseCertificationsCAQCInner } from './CertificationsTvList200ResponseCertificationsCAQCInner';
import {
    CertificationsTvList200ResponseCertificationsCAQCInnerFromJSON,
    CertificationsTvList200ResponseCertificationsCAQCInnerFromJSONTyped,
    CertificationsTvList200ResponseCertificationsCAQCInnerToJSON,
} from './CertificationsTvList200ResponseCertificationsCAQCInner';
import type { CertificationsTvList200ResponseCertificationsILInner } from './CertificationsTvList200ResponseCertificationsILInner';
import {
    CertificationsTvList200ResponseCertificationsILInnerFromJSON,
    CertificationsTvList200ResponseCertificationsILInnerFromJSONTyped,
    CertificationsTvList200ResponseCertificationsILInnerToJSON,
} from './CertificationsTvList200ResponseCertificationsILInner';
import type { CertificationsTvList200ResponseCertificationsNOInner } from './CertificationsTvList200ResponseCertificationsNOInner';
import {
    CertificationsTvList200ResponseCertificationsNOInnerFromJSON,
    CertificationsTvList200ResponseCertificationsNOInnerFromJSONTyped,
    CertificationsTvList200ResponseCertificationsNOInnerToJSON,
} from './CertificationsTvList200ResponseCertificationsNOInner';
import type { CertificationMovieList200ResponseCertificationsCAQCInner } from './CertificationMovieList200ResponseCertificationsCAQCInner';
import {
    CertificationMovieList200ResponseCertificationsCAQCInnerFromJSON,
    CertificationMovieList200ResponseCertificationsCAQCInnerFromJSONTyped,
    CertificationMovieList200ResponseCertificationsCAQCInnerToJSON,
} from './CertificationMovieList200ResponseCertificationsCAQCInner';
import type { CertificationsTvList200ResponseCertificationsLTInner } from './CertificationsTvList200ResponseCertificationsLTInner';
import {
    CertificationsTvList200ResponseCertificationsLTInnerFromJSON,
    CertificationsTvList200ResponseCertificationsLTInnerFromJSONTyped,
    CertificationsTvList200ResponseCertificationsLTInnerToJSON,
} from './CertificationsTvList200ResponseCertificationsLTInner';
import type { CertificationsTvList200ResponseCertificationsPLInner } from './CertificationsTvList200ResponseCertificationsPLInner';
import {
    CertificationsTvList200ResponseCertificationsPLInnerFromJSON,
    CertificationsTvList200ResponseCertificationsPLInnerFromJSONTyped,
    CertificationsTvList200ResponseCertificationsPLInnerToJSON,
} from './CertificationsTvList200ResponseCertificationsPLInner';
import type { CertificationsTvList200ResponseCertificationsPRInner } from './CertificationsTvList200ResponseCertificationsPRInner';
import {
    CertificationsTvList200ResponseCertificationsPRInnerFromJSON,
    CertificationsTvList200ResponseCertificationsPRInnerFromJSONTyped,
    CertificationsTvList200ResponseCertificationsPRInnerToJSON,
} from './CertificationsTvList200ResponseCertificationsPRInner';
import type { CertificationsTvList200ResponseCertificationsTWInner } from './CertificationsTvList200ResponseCertificationsTWInner';
import {
    CertificationsTvList200ResponseCertificationsTWInnerFromJSON,
    CertificationsTvList200ResponseCertificationsTWInnerFromJSONTyped,
    CertificationsTvList200ResponseCertificationsTWInnerToJSON,
} from './CertificationsTvList200ResponseCertificationsTWInner';
import type { CertificationsTvList200ResponseCertificationsHUInner } from './CertificationsTvList200ResponseCertificationsHUInner';
import {
    CertificationsTvList200ResponseCertificationsHUInnerFromJSON,
    CertificationsTvList200ResponseCertificationsHUInnerFromJSONTyped,
    CertificationsTvList200ResponseCertificationsHUInnerToJSON,
} from './CertificationsTvList200ResponseCertificationsHUInner';
import type { CertificationsTvList200ResponseCertificationsMXInner } from './CertificationsTvList200ResponseCertificationsMXInner';
import {
    CertificationsTvList200ResponseCertificationsMXInnerFromJSON,
    CertificationsTvList200ResponseCertificationsMXInnerFromJSONTyped,
    CertificationsTvList200ResponseCertificationsMXInnerToJSON,
} from './CertificationsTvList200ResponseCertificationsMXInner';
import type { CertificationsTvList200ResponseCertificationsKRInner } from './CertificationsTvList200ResponseCertificationsKRInner';
import {
    CertificationsTvList200ResponseCertificationsKRInnerFromJSON,
    CertificationsTvList200ResponseCertificationsKRInnerFromJSONTyped,
    CertificationsTvList200ResponseCertificationsKRInnerToJSON,
} from './CertificationsTvList200ResponseCertificationsKRInner';
import type { CertificationsTvList200ResponseCertificationsBGInner } from './CertificationsTvList200ResponseCertificationsBGInner';
import {
    CertificationsTvList200ResponseCertificationsBGInnerFromJSON,
    CertificationsTvList200ResponseCertificationsBGInnerFromJSONTyped,
    CertificationsTvList200ResponseCertificationsBGInnerToJSON,
} from './CertificationsTvList200ResponseCertificationsBGInner';
import type { CertificationsTvList200ResponseCertificationsFIInner } from './CertificationsTvList200ResponseCertificationsFIInner';
import {
    CertificationsTvList200ResponseCertificationsFIInnerFromJSON,
    CertificationsTvList200ResponseCertificationsFIInnerFromJSONTyped,
    CertificationsTvList200ResponseCertificationsFIInnerToJSON,
} from './CertificationsTvList200ResponseCertificationsFIInner';
import type { CertificationsTvList200ResponseCertificationsIDInner } from './CertificationsTvList200ResponseCertificationsIDInner';
import {
    CertificationsTvList200ResponseCertificationsIDInnerFromJSON,
    CertificationsTvList200ResponseCertificationsIDInnerFromJSONTyped,
    CertificationsTvList200ResponseCertificationsIDInnerToJSON,
} from './CertificationsTvList200ResponseCertificationsIDInner';
import type { CertificationsTvList200ResponseCertificationsRUInner } from './CertificationsTvList200ResponseCertificationsRUInner';
import {
    CertificationsTvList200ResponseCertificationsRUInnerFromJSON,
    CertificationsTvList200ResponseCertificationsRUInnerFromJSONTyped,
    CertificationsTvList200ResponseCertificationsRUInnerToJSON,
} from './CertificationsTvList200ResponseCertificationsRUInner';
import type { CertificationsTvList200ResponseCertificationsUSInner } from './CertificationsTvList200ResponseCertificationsUSInner';
import {
    CertificationsTvList200ResponseCertificationsUSInnerFromJSON,
    CertificationsTvList200ResponseCertificationsUSInnerFromJSONTyped,
    CertificationsTvList200ResponseCertificationsUSInnerToJSON,
} from './CertificationsTvList200ResponseCertificationsUSInner';
import type { CertificationsTvList200ResponseCertificationsTHInner } from './CertificationsTvList200ResponseCertificationsTHInner';
import {
    CertificationsTvList200ResponseCertificationsTHInnerFromJSON,
    CertificationsTvList200ResponseCertificationsTHInnerFromJSONTyped,
    CertificationsTvList200ResponseCertificationsTHInnerToJSON,
} from './CertificationsTvList200ResponseCertificationsTHInner';
import type { CertificationsTvList200ResponseCertificationsZAInner } from './CertificationsTvList200ResponseCertificationsZAInner';
import {
    CertificationsTvList200ResponseCertificationsZAInnerFromJSON,
    CertificationsTvList200ResponseCertificationsZAInnerFromJSONTyped,
    CertificationsTvList200ResponseCertificationsZAInnerToJSON,
} from './CertificationsTvList200ResponseCertificationsZAInner';
import type { CertificationsTvList200ResponseCertificationsARInner } from './CertificationsTvList200ResponseCertificationsARInner';
import {
    CertificationsTvList200ResponseCertificationsARInnerFromJSON,
    CertificationsTvList200ResponseCertificationsARInnerFromJSONTyped,
    CertificationsTvList200ResponseCertificationsARInnerToJSON,
} from './CertificationsTvList200ResponseCertificationsARInner';
import type { CertificationsTvList200ResponseCertificationsSEInner } from './CertificationsTvList200ResponseCertificationsSEInner';
import {
    CertificationsTvList200ResponseCertificationsSEInnerFromJSON,
    CertificationsTvList200ResponseCertificationsSEInnerFromJSONTyped,
    CertificationsTvList200ResponseCertificationsSEInnerToJSON,
} from './CertificationsTvList200ResponseCertificationsSEInner';
import type { CertificationsTvList200ResponseCertificationsTRInner } from './CertificationsTvList200ResponseCertificationsTRInner';
import {
    CertificationsTvList200ResponseCertificationsTRInnerFromJSON,
    CertificationsTvList200ResponseCertificationsTRInnerFromJSONTyped,
    CertificationsTvList200ResponseCertificationsTRInnerToJSON,
} from './CertificationsTvList200ResponseCertificationsTRInner';
import type { CertificationsTvList200ResponseCertificationsAUInner } from './CertificationsTvList200ResponseCertificationsAUInner';
import {
    CertificationsTvList200ResponseCertificationsAUInnerFromJSON,
    CertificationsTvList200ResponseCertificationsAUInnerFromJSONTyped,
    CertificationsTvList200ResponseCertificationsAUInnerToJSON,
} from './CertificationsTvList200ResponseCertificationsAUInner';
import type { CertificationsTvList200ResponseCertificationsBRInner } from './CertificationsTvList200ResponseCertificationsBRInner';
import {
    CertificationsTvList200ResponseCertificationsBRInnerFromJSON,
    CertificationsTvList200ResponseCertificationsBRInnerFromJSONTyped,
    CertificationsTvList200ResponseCertificationsBRInnerToJSON,
} from './CertificationsTvList200ResponseCertificationsBRInner';
import type { CertificationsTvList200ResponseCertificationsPTInner } from './CertificationsTvList200ResponseCertificationsPTInner';
import {
    CertificationsTvList200ResponseCertificationsPTInnerFromJSON,
    CertificationsTvList200ResponseCertificationsPTInnerFromJSONTyped,
    CertificationsTvList200ResponseCertificationsPTInnerToJSON,
} from './CertificationsTvList200ResponseCertificationsPTInner';
import type { CertificationsTvList200ResponseCertificationsGRInner } from './CertificationsTvList200ResponseCertificationsGRInner';
import {
    CertificationsTvList200ResponseCertificationsGRInnerFromJSON,
    CertificationsTvList200ResponseCertificationsGRInnerFromJSONTyped,
    CertificationsTvList200ResponseCertificationsGRInnerToJSON,
} from './CertificationsTvList200ResponseCertificationsGRInner';
import type { CertificationsTvList200ResponseCertificationsGBInner } from './CertificationsTvList200ResponseCertificationsGBInner';
import {
    CertificationsTvList200ResponseCertificationsGBInnerFromJSON,
    CertificationsTvList200ResponseCertificationsGBInnerFromJSONTyped,
    CertificationsTvList200ResponseCertificationsGBInnerToJSON,
} from './CertificationsTvList200ResponseCertificationsGBInner';

/**
 * 
 * @export
 * @interface CertificationsTvList200ResponseCertifications
 */
export interface CertificationsTvList200ResponseCertifications {
    /**
     * 
     * @type {Array<CertificationsTvList200ResponseCertificationsAUInner>}
     * @memberof CertificationsTvList200ResponseCertifications
     */
    AU?: Array<CertificationsTvList200ResponseCertificationsAUInner>;
    /**
     * 
     * @type {Array<CertificationsTvList200ResponseCertificationsBRInner>}
     * @memberof CertificationsTvList200ResponseCertifications
     */
    BR?: Array<CertificationsTvList200ResponseCertificationsBRInner>;
    /**
     * 
     * @type {Array<CertificationsTvList200ResponseCertificationsCAInner>}
     * @memberof CertificationsTvList200ResponseCertifications
     */
    CA?: Array<CertificationsTvList200ResponseCertificationsCAInner>;
    /**
     * 
     * @type {Array<CertificationsTvList200ResponseCertificationsCAQCInner>}
     * @memberof CertificationsTvList200ResponseCertifications
     */
    CA_QC?: Array<CertificationsTvList200ResponseCertificationsCAQCInner>;
    /**
     * 
     * @type {Array<CertificationsTvList200ResponseCertificationsDEInner>}
     * @memberof CertificationsTvList200ResponseCertifications
     */
    DE?: Array<CertificationsTvList200ResponseCertificationsDEInner>;
    /**
     * 
     * @type {Array<CertificationMovieList200ResponseCertificationsCAQCInner>}
     * @memberof CertificationsTvList200ResponseCertifications
     */
    ES?: Array<CertificationMovieList200ResponseCertificationsCAQCInner>;
    /**
     * 
     * @type {Array<CertificationMovieList200ResponseCertificationsCAQCInner>}
     * @memberof CertificationsTvList200ResponseCertifications
     */
    FR?: Array<CertificationMovieList200ResponseCertificationsCAQCInner>;
    /**
     * 
     * @type {Array<CertificationsTvList200ResponseCertificationsGBInner>}
     * @memberof CertificationsTvList200ResponseCertifications
     */
    GB?: Array<CertificationsTvList200ResponseCertificationsGBInner>;
    /**
     * 
     * @type {Array<CertificationsTvList200ResponseCertificationsHUInner>}
     * @memberof CertificationsTvList200ResponseCertifications
     */
    HU?: Array<CertificationsTvList200ResponseCertificationsHUInner>;
    /**
     * 
     * @type {Array<CertificationsTvList200ResponseCertificationsKRInner>}
     * @memberof CertificationsTvList200ResponseCertifications
     */
    KR?: Array<CertificationsTvList200ResponseCertificationsKRInner>;
    /**
     * 
     * @type {Array<CertificationsTvList200ResponseCertificationsLTInner>}
     * @memberof CertificationsTvList200ResponseCertifications
     */
    LT?: Array<CertificationsTvList200ResponseCertificationsLTInner>;
    /**
     * 
     * @type {Array<CertificationMovieList200ResponseCertificationsCAQCInner>}
     * @memberof CertificationsTvList200ResponseCertifications
     */
    NL?: Array<CertificationMovieList200ResponseCertificationsCAQCInner>;
    /**
     * 
     * @type {Array<CertificationMovieList200ResponseCertificationsCAQCInner>}
     * @memberof CertificationsTvList200ResponseCertifications
     */
    PH?: Array<CertificationMovieList200ResponseCertificationsCAQCInner>;
    /**
     * 
     * @type {Array<CertificationsTvList200ResponseCertificationsPTInner>}
     * @memberof CertificationsTvList200ResponseCertifications
     */
    PT?: Array<CertificationsTvList200ResponseCertificationsPTInner>;
    /**
     * 
     * @type {Array<CertificationsTvList200ResponseCertificationsRUInner>}
     * @memberof CertificationsTvList200ResponseCertifications
     */
    RU?: Array<CertificationsTvList200ResponseCertificationsRUInner>;
    /**
     * 
     * @type {Array<CertificationMovieList200ResponseCertificationsCAQCInner>}
     * @memberof CertificationsTvList200ResponseCertifications
     */
    SK?: Array<CertificationMovieList200ResponseCertificationsCAQCInner>;
    /**
     * 
     * @type {Array<CertificationsTvList200ResponseCertificationsTHInner>}
     * @memberof CertificationsTvList200ResponseCertifications
     */
    TH?: Array<CertificationsTvList200ResponseCertificationsTHInner>;
    /**
     * 
     * @type {Array<CertificationsTvList200ResponseCertificationsUSInner>}
     * @memberof CertificationsTvList200ResponseCertifications
     */
    US?: Array<CertificationsTvList200ResponseCertificationsUSInner>;
    /**
     * 
     * @type {Array<CertificationsTvList200ResponseCertificationsITInner>}
     * @memberof CertificationsTvList200ResponseCertifications
     */
    IT?: Array<CertificationsTvList200ResponseCertificationsITInner>;
    /**
     * 
     * @type {Array<CertificationsTvList200ResponseCertificationsFIInner>}
     * @memberof CertificationsTvList200ResponseCertifications
     */
    FI?: Array<CertificationsTvList200ResponseCertificationsFIInner>;
    /**
     * 
     * @type {Array<CertificationsTvList200ResponseCertificationsMYInner>}
     * @memberof CertificationsTvList200ResponseCertifications
     */
    MY?: Array<CertificationsTvList200ResponseCertificationsMYInner>;
    /**
     * 
     * @type {Array<CertificationsTvList200ResponseCertificationsNZInner>}
     * @memberof CertificationsTvList200ResponseCertifications
     */
    NZ?: Array<CertificationsTvList200ResponseCertificationsNZInner>;
    /**
     * 
     * @type {Array<CertificationsTvList200ResponseCertificationsNOInner>}
     * @memberof CertificationsTvList200ResponseCertifications
     */
    NO?: Array<CertificationsTvList200ResponseCertificationsNOInner>;
    /**
     * 
     * @type {Array<CertificationsTvList200ResponseCertificationsBGInner>}
     * @memberof CertificationsTvList200ResponseCertifications
     */
    BG?: Array<CertificationsTvList200ResponseCertificationsBGInner>;
    /**
     * 
     * @type {Array<CertificationsTvList200ResponseCertificationsMXInner>}
     * @memberof CertificationsTvList200ResponseCertifications
     */
    MX?: Array<CertificationsTvList200ResponseCertificationsMXInner>;
    /**
     * 
     * @type {Array<CertificationsTvList200ResponseCertificationsINInner>}
     * @memberof CertificationsTvList200ResponseCertifications
     */
    IN?: Array<CertificationsTvList200ResponseCertificationsINInner>;
    /**
     * 
     * @type {Array<CertificationsTvList200ResponseCertificationsDKInner>}
     * @memberof CertificationsTvList200ResponseCertifications
     */
    DK?: Array<CertificationsTvList200ResponseCertificationsDKInner>;
    /**
     * 
     * @type {Array<CertificationsTvList200ResponseCertificationsSEInner>}
     * @memberof CertificationsTvList200ResponseCertifications
     */
    SE?: Array<CertificationsTvList200ResponseCertificationsSEInner>;
    /**
     * 
     * @type {Array<CertificationsTvList200ResponseCertificationsIDInner>}
     * @memberof CertificationsTvList200ResponseCertifications
     */
    ID?: Array<CertificationsTvList200ResponseCertificationsIDInner>;
    /**
     * 
     * @type {Array<CertificationsTvList200ResponseCertificationsTRInner>}
     * @memberof CertificationsTvList200ResponseCertifications
     */
    TR?: Array<CertificationsTvList200ResponseCertificationsTRInner>;
    /**
     * 
     * @type {Array<CertificationsTvList200ResponseCertificationsARInner>}
     * @memberof CertificationsTvList200ResponseCertifications
     */
    AR?: Array<CertificationsTvList200ResponseCertificationsARInner>;
    /**
     * 
     * @type {Array<CertificationsTvList200ResponseCertificationsPLInner>}
     * @memberof CertificationsTvList200ResponseCertifications
     */
    PL?: Array<CertificationsTvList200ResponseCertificationsPLInner>;
    /**
     * 
     * @type {Array<CertificationsTvList200ResponseCertificationsMAInner>}
     * @memberof CertificationsTvList200ResponseCertifications
     */
    MA?: Array<CertificationsTvList200ResponseCertificationsMAInner>;
    /**
     * 
     * @type {Array<CertificationsTvList200ResponseCertificationsGRInner>}
     * @memberof CertificationsTvList200ResponseCertifications
     */
    GR?: Array<CertificationsTvList200ResponseCertificationsGRInner>;
    /**
     * 
     * @type {Array<CertificationsTvList200ResponseCertificationsILInner>}
     * @memberof CertificationsTvList200ResponseCertifications
     */
    IL?: Array<CertificationsTvList200ResponseCertificationsILInner>;
    /**
     * 
     * @type {Array<CertificationsTvList200ResponseCertificationsTWInner>}
     * @memberof CertificationsTvList200ResponseCertifications
     */
    TW?: Array<CertificationsTvList200ResponseCertificationsTWInner>;
    /**
     * 
     * @type {Array<CertificationsTvList200ResponseCertificationsZAInner>}
     * @memberof CertificationsTvList200ResponseCertifications
     */
    ZA?: Array<CertificationsTvList200ResponseCertificationsZAInner>;
    /**
     * 
     * @type {Array<CertificationMovieList200ResponseCertificationsPRInner>}
     * @memberof CertificationsTvList200ResponseCertifications
     */
    SG?: Array<CertificationMovieList200ResponseCertificationsPRInner>;
    /**
     * 
     * @type {Array<CertificationsTvList200ResponseCertificationsPRInner>}
     * @memberof CertificationsTvList200ResponseCertifications
     */
    PR?: Array<CertificationsTvList200ResponseCertificationsPRInner>;
    /**
     * 
     * @type {Array<CertificationsTvList200ResponseCertificationsPRInner>}
     * @memberof CertificationsTvList200ResponseCertifications
     */
    VI?: Array<CertificationsTvList200ResponseCertificationsPRInner>;
}

/**
 * Check if a given object implements the CertificationsTvList200ResponseCertifications interface.
 */
export function instanceOfCertificationsTvList200ResponseCertifications(value: object): value is CertificationsTvList200ResponseCertifications {
    return true;
}

export function CertificationsTvList200ResponseCertificationsFromJSON(json: any): CertificationsTvList200ResponseCertifications {
    return CertificationsTvList200ResponseCertificationsFromJSONTyped(json, false);
}

export function CertificationsTvList200ResponseCertificationsFromJSONTyped(json: any, ignoreDiscriminator: boolean): CertificationsTvList200ResponseCertifications {
    if (json == null) {
        return json;
    }
    return {
        
        'AU': json['AU'] == null ? undefined : ((json['AU'] as Array<any>).map(CertificationsTvList200ResponseCertificationsAUInnerFromJSON)),
        'BR': json['BR'] == null ? undefined : ((json['BR'] as Array<any>).map(CertificationsTvList200ResponseCertificationsBRInnerFromJSON)),
        'CA': json['CA'] == null ? undefined : ((json['CA'] as Array<any>).map(CertificationsTvList200ResponseCertificationsCAInnerFromJSON)),
        'CA_QC': json['CA-QC'] == null ? undefined : ((json['CA-QC'] as Array<any>).map(CertificationsTvList200ResponseCertificationsCAQCInnerFromJSON)),
        'DE': json['DE'] == null ? undefined : ((json['DE'] as Array<any>).map(CertificationsTvList200ResponseCertificationsDEInnerFromJSON)),
        'ES': json['ES'] == null ? undefined : ((json['ES'] as Array<any>).map(CertificationMovieList200ResponseCertificationsCAQCInnerFromJSON)),
        'FR': json['FR'] == null ? undefined : ((json['FR'] as Array<any>).map(CertificationMovieList200ResponseCertificationsCAQCInnerFromJSON)),
        'GB': json['GB'] == null ? undefined : ((json['GB'] as Array<any>).map(CertificationsTvList200ResponseCertificationsGBInnerFromJSON)),
        'HU': json['HU'] == null ? undefined : ((json['HU'] as Array<any>).map(CertificationsTvList200ResponseCertificationsHUInnerFromJSON)),
        'KR': json['KR'] == null ? undefined : ((json['KR'] as Array<any>).map(CertificationsTvList200ResponseCertificationsKRInnerFromJSON)),
        'LT': json['LT'] == null ? undefined : ((json['LT'] as Array<any>).map(CertificationsTvList200ResponseCertificationsLTInnerFromJSON)),
        'NL': json['NL'] == null ? undefined : ((json['NL'] as Array<any>).map(CertificationMovieList200ResponseCertificationsCAQCInnerFromJSON)),
        'PH': json['PH'] == null ? undefined : ((json['PH'] as Array<any>).map(CertificationMovieList200ResponseCertificationsCAQCInnerFromJSON)),
        'PT': json['PT'] == null ? undefined : ((json['PT'] as Array<any>).map(CertificationsTvList200ResponseCertificationsPTInnerFromJSON)),
        'RU': json['RU'] == null ? undefined : ((json['RU'] as Array<any>).map(CertificationsTvList200ResponseCertificationsRUInnerFromJSON)),
        'SK': json['SK'] == null ? undefined : ((json['SK'] as Array<any>).map(CertificationMovieList200ResponseCertificationsCAQCInnerFromJSON)),
        'TH': json['TH'] == null ? undefined : ((json['TH'] as Array<any>).map(CertificationsTvList200ResponseCertificationsTHInnerFromJSON)),
        'US': json['US'] == null ? undefined : ((json['US'] as Array<any>).map(CertificationsTvList200ResponseCertificationsUSInnerFromJSON)),
        'IT': json['IT'] == null ? undefined : ((json['IT'] as Array<any>).map(CertificationsTvList200ResponseCertificationsITInnerFromJSON)),
        'FI': json['FI'] == null ? undefined : ((json['FI'] as Array<any>).map(CertificationsTvList200ResponseCertificationsFIInnerFromJSON)),
        'MY': json['MY'] == null ? undefined : ((json['MY'] as Array<any>).map(CertificationsTvList200ResponseCertificationsMYInnerFromJSON)),
        'NZ': json['NZ'] == null ? undefined : ((json['NZ'] as Array<any>).map(CertificationsTvList200ResponseCertificationsNZInnerFromJSON)),
        'NO': json['NO'] == null ? undefined : ((json['NO'] as Array<any>).map(CertificationsTvList200ResponseCertificationsNOInnerFromJSON)),
        'BG': json['BG'] == null ? undefined : ((json['BG'] as Array<any>).map(CertificationsTvList200ResponseCertificationsBGInnerFromJSON)),
        'MX': json['MX'] == null ? undefined : ((json['MX'] as Array<any>).map(CertificationsTvList200ResponseCertificationsMXInnerFromJSON)),
        'IN': json['IN'] == null ? undefined : ((json['IN'] as Array<any>).map(CertificationsTvList200ResponseCertificationsINInnerFromJSON)),
        'DK': json['DK'] == null ? undefined : ((json['DK'] as Array<any>).map(CertificationsTvList200ResponseCertificationsDKInnerFromJSON)),
        'SE': json['SE'] == null ? undefined : ((json['SE'] as Array<any>).map(CertificationsTvList200ResponseCertificationsSEInnerFromJSON)),
        'ID': json['ID'] == null ? undefined : ((json['ID'] as Array<any>).map(CertificationsTvList200ResponseCertificationsIDInnerFromJSON)),
        'TR': json['TR'] == null ? undefined : ((json['TR'] as Array<any>).map(CertificationsTvList200ResponseCertificationsTRInnerFromJSON)),
        'AR': json['AR'] == null ? undefined : ((json['AR'] as Array<any>).map(CertificationsTvList200ResponseCertificationsARInnerFromJSON)),
        'PL': json['PL'] == null ? undefined : ((json['PL'] as Array<any>).map(CertificationsTvList200ResponseCertificationsPLInnerFromJSON)),
        'MA': json['MA'] == null ? undefined : ((json['MA'] as Array<any>).map(CertificationsTvList200ResponseCertificationsMAInnerFromJSON)),
        'GR': json['GR'] == null ? undefined : ((json['GR'] as Array<any>).map(CertificationsTvList200ResponseCertificationsGRInnerFromJSON)),
        'IL': json['IL'] == null ? undefined : ((json['IL'] as Array<any>).map(CertificationsTvList200ResponseCertificationsILInnerFromJSON)),
        'TW': json['TW'] == null ? undefined : ((json['TW'] as Array<any>).map(CertificationsTvList200ResponseCertificationsTWInnerFromJSON)),
        'ZA': json['ZA'] == null ? undefined : ((json['ZA'] as Array<any>).map(CertificationsTvList200ResponseCertificationsZAInnerFromJSON)),
        'SG': json['SG'] == null ? undefined : ((json['SG'] as Array<any>).map(CertificationMovieList200ResponseCertificationsPRInnerFromJSON)),
        'PR': json['PR'] == null ? undefined : ((json['PR'] as Array<any>).map(CertificationsTvList200ResponseCertificationsPRInnerFromJSON)),
        'VI': json['VI'] == null ? undefined : ((json['VI'] as Array<any>).map(CertificationsTvList200ResponseCertificationsPRInnerFromJSON)),
    };
}

export function CertificationsTvList200ResponseCertificationsToJSON(value?: CertificationsTvList200ResponseCertifications | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'AU': value['AU'] == null ? undefined : ((value['AU'] as Array<any>).map(CertificationsTvList200ResponseCertificationsAUInnerToJSON)),
        'BR': value['BR'] == null ? undefined : ((value['BR'] as Array<any>).map(CertificationsTvList200ResponseCertificationsBRInnerToJSON)),
        'CA': value['CA'] == null ? undefined : ((value['CA'] as Array<any>).map(CertificationsTvList200ResponseCertificationsCAInnerToJSON)),
        'CA-QC': value['CA_QC'] == null ? undefined : ((value['CA_QC'] as Array<any>).map(CertificationsTvList200ResponseCertificationsCAQCInnerToJSON)),
        'DE': value['DE'] == null ? undefined : ((value['DE'] as Array<any>).map(CertificationsTvList200ResponseCertificationsDEInnerToJSON)),
        'ES': value['ES'] == null ? undefined : ((value['ES'] as Array<any>).map(CertificationMovieList200ResponseCertificationsCAQCInnerToJSON)),
        'FR': value['FR'] == null ? undefined : ((value['FR'] as Array<any>).map(CertificationMovieList200ResponseCertificationsCAQCInnerToJSON)),
        'GB': value['GB'] == null ? undefined : ((value['GB'] as Array<any>).map(CertificationsTvList200ResponseCertificationsGBInnerToJSON)),
        'HU': value['HU'] == null ? undefined : ((value['HU'] as Array<any>).map(CertificationsTvList200ResponseCertificationsHUInnerToJSON)),
        'KR': value['KR'] == null ? undefined : ((value['KR'] as Array<any>).map(CertificationsTvList200ResponseCertificationsKRInnerToJSON)),
        'LT': value['LT'] == null ? undefined : ((value['LT'] as Array<any>).map(CertificationsTvList200ResponseCertificationsLTInnerToJSON)),
        'NL': value['NL'] == null ? undefined : ((value['NL'] as Array<any>).map(CertificationMovieList200ResponseCertificationsCAQCInnerToJSON)),
        'PH': value['PH'] == null ? undefined : ((value['PH'] as Array<any>).map(CertificationMovieList200ResponseCertificationsCAQCInnerToJSON)),
        'PT': value['PT'] == null ? undefined : ((value['PT'] as Array<any>).map(CertificationsTvList200ResponseCertificationsPTInnerToJSON)),
        'RU': value['RU'] == null ? undefined : ((value['RU'] as Array<any>).map(CertificationsTvList200ResponseCertificationsRUInnerToJSON)),
        'SK': value['SK'] == null ? undefined : ((value['SK'] as Array<any>).map(CertificationMovieList200ResponseCertificationsCAQCInnerToJSON)),
        'TH': value['TH'] == null ? undefined : ((value['TH'] as Array<any>).map(CertificationsTvList200ResponseCertificationsTHInnerToJSON)),
        'US': value['US'] == null ? undefined : ((value['US'] as Array<any>).map(CertificationsTvList200ResponseCertificationsUSInnerToJSON)),
        'IT': value['IT'] == null ? undefined : ((value['IT'] as Array<any>).map(CertificationsTvList200ResponseCertificationsITInnerToJSON)),
        'FI': value['FI'] == null ? undefined : ((value['FI'] as Array<any>).map(CertificationsTvList200ResponseCertificationsFIInnerToJSON)),
        'MY': value['MY'] == null ? undefined : ((value['MY'] as Array<any>).map(CertificationsTvList200ResponseCertificationsMYInnerToJSON)),
        'NZ': value['NZ'] == null ? undefined : ((value['NZ'] as Array<any>).map(CertificationsTvList200ResponseCertificationsNZInnerToJSON)),
        'NO': value['NO'] == null ? undefined : ((value['NO'] as Array<any>).map(CertificationsTvList200ResponseCertificationsNOInnerToJSON)),
        'BG': value['BG'] == null ? undefined : ((value['BG'] as Array<any>).map(CertificationsTvList200ResponseCertificationsBGInnerToJSON)),
        'MX': value['MX'] == null ? undefined : ((value['MX'] as Array<any>).map(CertificationsTvList200ResponseCertificationsMXInnerToJSON)),
        'IN': value['IN'] == null ? undefined : ((value['IN'] as Array<any>).map(CertificationsTvList200ResponseCertificationsINInnerToJSON)),
        'DK': value['DK'] == null ? undefined : ((value['DK'] as Array<any>).map(CertificationsTvList200ResponseCertificationsDKInnerToJSON)),
        'SE': value['SE'] == null ? undefined : ((value['SE'] as Array<any>).map(CertificationsTvList200ResponseCertificationsSEInnerToJSON)),
        'ID': value['ID'] == null ? undefined : ((value['ID'] as Array<any>).map(CertificationsTvList200ResponseCertificationsIDInnerToJSON)),
        'TR': value['TR'] == null ? undefined : ((value['TR'] as Array<any>).map(CertificationsTvList200ResponseCertificationsTRInnerToJSON)),
        'AR': value['AR'] == null ? undefined : ((value['AR'] as Array<any>).map(CertificationsTvList200ResponseCertificationsARInnerToJSON)),
        'PL': value['PL'] == null ? undefined : ((value['PL'] as Array<any>).map(CertificationsTvList200ResponseCertificationsPLInnerToJSON)),
        'MA': value['MA'] == null ? undefined : ((value['MA'] as Array<any>).map(CertificationsTvList200ResponseCertificationsMAInnerToJSON)),
        'GR': value['GR'] == null ? undefined : ((value['GR'] as Array<any>).map(CertificationsTvList200ResponseCertificationsGRInnerToJSON)),
        'IL': value['IL'] == null ? undefined : ((value['IL'] as Array<any>).map(CertificationsTvList200ResponseCertificationsILInnerToJSON)),
        'TW': value['TW'] == null ? undefined : ((value['TW'] as Array<any>).map(CertificationsTvList200ResponseCertificationsTWInnerToJSON)),
        'ZA': value['ZA'] == null ? undefined : ((value['ZA'] as Array<any>).map(CertificationsTvList200ResponseCertificationsZAInnerToJSON)),
        'SG': value['SG'] == null ? undefined : ((value['SG'] as Array<any>).map(CertificationMovieList200ResponseCertificationsPRInnerToJSON)),
        'PR': value['PR'] == null ? undefined : ((value['PR'] as Array<any>).map(CertificationsTvList200ResponseCertificationsPRInnerToJSON)),
        'VI': value['VI'] == null ? undefined : ((value['VI'] as Array<any>).map(CertificationsTvList200ResponseCertificationsPRInnerToJSON)),
    };
}

