/* tslint:disable */
/* eslint-disable */
/**
 * TMDB API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ChangesPeopleList200ResponseResultsInner } from './ChangesPeopleList200ResponseResultsInner';
import {
    ChangesPeopleList200ResponseResultsInnerFromJSON,
    ChangesPeopleList200ResponseResultsInnerFromJSONTyped,
    ChangesPeopleList200ResponseResultsInnerToJSON,
} from './ChangesPeopleList200ResponseResultsInner';

/**
 * 
 * @export
 * @interface ChangesPeopleList200Response
 */
export interface ChangesPeopleList200Response {
    /**
     * 
     * @type {Array<ChangesPeopleList200ResponseResultsInner>}
     * @memberof ChangesPeopleList200Response
     */
    results?: Array<ChangesPeopleList200ResponseResultsInner>;
    /**
     * 
     * @type {number}
     * @memberof ChangesPeopleList200Response
     */
    page?: number;
    /**
     * 
     * @type {number}
     * @memberof ChangesPeopleList200Response
     */
    total_pages?: number;
    /**
     * 
     * @type {number}
     * @memberof ChangesPeopleList200Response
     */
    total_results?: number;
}

/**
 * Check if a given object implements the ChangesPeopleList200Response interface.
 */
export function instanceOfChangesPeopleList200Response(value: object): value is ChangesPeopleList200Response {
    return true;
}

export function ChangesPeopleList200ResponseFromJSON(json: any): ChangesPeopleList200Response {
    return ChangesPeopleList200ResponseFromJSONTyped(json, false);
}

export function ChangesPeopleList200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ChangesPeopleList200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'results': json['results'] == null ? undefined : ((json['results'] as Array<any>).map(ChangesPeopleList200ResponseResultsInnerFromJSON)),
        'page': json['page'] == null ? undefined : json['page'],
        'total_pages': json['total_pages'] == null ? undefined : json['total_pages'],
        'total_results': json['total_results'] == null ? undefined : json['total_results'],
    };
}

export function ChangesPeopleList200ResponseToJSON(value?: ChangesPeopleList200Response | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'results': value['results'] == null ? undefined : ((value['results'] as Array<any>).map(ChangesPeopleList200ResponseResultsInnerToJSON)),
        'page': value['page'],
        'total_pages': value['total_pages'],
        'total_results': value['total_results'],
    };
}

