/* tslint:disable */
/* eslint-disable */
/**
 * TMDB API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CompanyDetails200Response
 */
export interface CompanyDetails200Response {
    /**
     * 
     * @type {string}
     * @memberof CompanyDetails200Response
     */
    description?: string;
    /**
     * 
     * @type {string}
     * @memberof CompanyDetails200Response
     */
    headquarters?: string;
    /**
     * 
     * @type {string}
     * @memberof CompanyDetails200Response
     */
    homepage?: string;
    /**
     * 
     * @type {number}
     * @memberof CompanyDetails200Response
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof CompanyDetails200Response
     */
    logo_path?: string;
    /**
     * 
     * @type {string}
     * @memberof CompanyDetails200Response
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof CompanyDetails200Response
     */
    origin_country?: string;
    /**
     * 
     * @type {any}
     * @memberof CompanyDetails200Response
     */
    parent_company?: any;
}

/**
 * Check if a given object implements the CompanyDetails200Response interface.
 */
export function instanceOfCompanyDetails200Response(value: object): value is CompanyDetails200Response {
    return true;
}

export function CompanyDetails200ResponseFromJSON(json: any): CompanyDetails200Response {
    return CompanyDetails200ResponseFromJSONTyped(json, false);
}

export function CompanyDetails200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): CompanyDetails200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'description': json['description'] == null ? undefined : json['description'],
        'headquarters': json['headquarters'] == null ? undefined : json['headquarters'],
        'homepage': json['homepage'] == null ? undefined : json['homepage'],
        'id': json['id'] == null ? undefined : json['id'],
        'logo_path': json['logo_path'] == null ? undefined : json['logo_path'],
        'name': json['name'] == null ? undefined : json['name'],
        'origin_country': json['origin_country'] == null ? undefined : json['origin_country'],
        'parent_company': json['parent_company'] == null ? undefined : json['parent_company'],
    };
}

export function CompanyDetails200ResponseToJSON(value?: CompanyDetails200Response | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'description': value['description'],
        'headquarters': value['headquarters'],
        'homepage': value['homepage'],
        'id': value['id'],
        'logo_path': value['logo_path'],
        'name': value['name'],
        'origin_country': value['origin_country'],
        'parent_company': value['parent_company'],
    };
}

