/* tslint:disable */
/* eslint-disable */
/**
 * TMDB API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ConfigurationDetails200ResponseImages
 */
export interface ConfigurationDetails200ResponseImages {
    /**
     * 
     * @type {string}
     * @memberof ConfigurationDetails200ResponseImages
     */
    base_url?: string;
    /**
     * 
     * @type {string}
     * @memberof ConfigurationDetails200ResponseImages
     */
    secure_base_url?: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof ConfigurationDetails200ResponseImages
     */
    backdrop_sizes?: Array<string>;
    /**
     * 
     * @type {Array<string>}
     * @memberof ConfigurationDetails200ResponseImages
     */
    logo_sizes?: Array<string>;
    /**
     * 
     * @type {Array<string>}
     * @memberof ConfigurationDetails200ResponseImages
     */
    poster_sizes?: Array<string>;
    /**
     * 
     * @type {Array<string>}
     * @memberof ConfigurationDetails200ResponseImages
     */
    profile_sizes?: Array<string>;
    /**
     * 
     * @type {Array<string>}
     * @memberof ConfigurationDetails200ResponseImages
     */
    still_sizes?: Array<string>;
}

/**
 * Check if a given object implements the ConfigurationDetails200ResponseImages interface.
 */
export function instanceOfConfigurationDetails200ResponseImages(value: object): value is ConfigurationDetails200ResponseImages {
    return true;
}

export function ConfigurationDetails200ResponseImagesFromJSON(json: any): ConfigurationDetails200ResponseImages {
    return ConfigurationDetails200ResponseImagesFromJSONTyped(json, false);
}

export function ConfigurationDetails200ResponseImagesFromJSONTyped(json: any, ignoreDiscriminator: boolean): ConfigurationDetails200ResponseImages {
    if (json == null) {
        return json;
    }
    return {
        
        'base_url': json['base_url'] == null ? undefined : json['base_url'],
        'secure_base_url': json['secure_base_url'] == null ? undefined : json['secure_base_url'],
        'backdrop_sizes': json['backdrop_sizes'] == null ? undefined : json['backdrop_sizes'],
        'logo_sizes': json['logo_sizes'] == null ? undefined : json['logo_sizes'],
        'poster_sizes': json['poster_sizes'] == null ? undefined : json['poster_sizes'],
        'profile_sizes': json['profile_sizes'] == null ? undefined : json['profile_sizes'],
        'still_sizes': json['still_sizes'] == null ? undefined : json['still_sizes'],
    };
}

export function ConfigurationDetails200ResponseImagesToJSON(value?: ConfigurationDetails200ResponseImages | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'base_url': value['base_url'],
        'secure_base_url': value['secure_base_url'],
        'backdrop_sizes': value['backdrop_sizes'],
        'logo_sizes': value['logo_sizes'],
        'poster_sizes': value['poster_sizes'],
        'profile_sizes': value['profile_sizes'],
        'still_sizes': value['still_sizes'],
    };
}

