/* tslint:disable */
/* eslint-disable */
/**
 * TMDB API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { CreditDetails200ResponseMediaSeasonsInner } from './CreditDetails200ResponseMediaSeasonsInner';
import {
    CreditDetails200ResponseMediaSeasonsInnerFromJSON,
    CreditDetails200ResponseMediaSeasonsInnerFromJSONTyped,
    CreditDetails200ResponseMediaSeasonsInnerToJSON,
} from './CreditDetails200ResponseMediaSeasonsInner';

/**
 * 
 * @export
 * @interface CreditDetails200ResponseMedia
 */
export interface CreditDetails200ResponseMedia {
    /**
     * 
     * @type {boolean}
     * @memberof CreditDetails200ResponseMedia
     */
    adult?: boolean;
    /**
     * 
     * @type {string}
     * @memberof CreditDetails200ResponseMedia
     */
    backdrop_path?: string;
    /**
     * 
     * @type {number}
     * @memberof CreditDetails200ResponseMedia
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof CreditDetails200ResponseMedia
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof CreditDetails200ResponseMedia
     */
    original_language?: string;
    /**
     * 
     * @type {string}
     * @memberof CreditDetails200ResponseMedia
     */
    original_name?: string;
    /**
     * 
     * @type {string}
     * @memberof CreditDetails200ResponseMedia
     */
    overview?: string;
    /**
     * 
     * @type {string}
     * @memberof CreditDetails200ResponseMedia
     */
    poster_path?: string;
    /**
     * 
     * @type {string}
     * @memberof CreditDetails200ResponseMedia
     */
    media_type?: string;
    /**
     * 
     * @type {Array<number>}
     * @memberof CreditDetails200ResponseMedia
     */
    genre_ids?: Array<number>;
    /**
     * 
     * @type {number}
     * @memberof CreditDetails200ResponseMedia
     */
    popularity?: number;
    /**
     * 
     * @type {string}
     * @memberof CreditDetails200ResponseMedia
     */
    first_air_date?: string;
    /**
     * 
     * @type {number}
     * @memberof CreditDetails200ResponseMedia
     */
    vote_average?: number;
    /**
     * 
     * @type {number}
     * @memberof CreditDetails200ResponseMedia
     */
    vote_count?: number;
    /**
     * 
     * @type {Array<string>}
     * @memberof CreditDetails200ResponseMedia
     */
    origin_country?: Array<string>;
    /**
     * 
     * @type {string}
     * @memberof CreditDetails200ResponseMedia
     */
    character?: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof CreditDetails200ResponseMedia
     */
    episodes?: Array<string>;
    /**
     * 
     * @type {Array<CreditDetails200ResponseMediaSeasonsInner>}
     * @memberof CreditDetails200ResponseMedia
     */
    seasons?: Array<CreditDetails200ResponseMediaSeasonsInner>;
}

/**
 * Check if a given object implements the CreditDetails200ResponseMedia interface.
 */
export function instanceOfCreditDetails200ResponseMedia(value: object): value is CreditDetails200ResponseMedia {
    return true;
}

export function CreditDetails200ResponseMediaFromJSON(json: any): CreditDetails200ResponseMedia {
    return CreditDetails200ResponseMediaFromJSONTyped(json, false);
}

export function CreditDetails200ResponseMediaFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreditDetails200ResponseMedia {
    if (json == null) {
        return json;
    }
    return {
        
        'adult': json['adult'] == null ? undefined : json['adult'],
        'backdrop_path': json['backdrop_path'] == null ? undefined : json['backdrop_path'],
        'id': json['id'] == null ? undefined : json['id'],
        'name': json['name'] == null ? undefined : json['name'],
        'original_language': json['original_language'] == null ? undefined : json['original_language'],
        'original_name': json['original_name'] == null ? undefined : json['original_name'],
        'overview': json['overview'] == null ? undefined : json['overview'],
        'poster_path': json['poster_path'] == null ? undefined : json['poster_path'],
        'media_type': json['media_type'] == null ? undefined : json['media_type'],
        'genre_ids': json['genre_ids'] == null ? undefined : json['genre_ids'],
        'popularity': json['popularity'] == null ? undefined : json['popularity'],
        'first_air_date': json['first_air_date'] == null ? undefined : json['first_air_date'],
        'vote_average': json['vote_average'] == null ? undefined : json['vote_average'],
        'vote_count': json['vote_count'] == null ? undefined : json['vote_count'],
        'origin_country': json['origin_country'] == null ? undefined : json['origin_country'],
        'character': json['character'] == null ? undefined : json['character'],
        'episodes': json['episodes'] == null ? undefined : json['episodes'],
        'seasons': json['seasons'] == null ? undefined : ((json['seasons'] as Array<any>).map(CreditDetails200ResponseMediaSeasonsInnerFromJSON)),
    };
}

export function CreditDetails200ResponseMediaToJSON(value?: CreditDetails200ResponseMedia | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'adult': value['adult'],
        'backdrop_path': value['backdrop_path'],
        'id': value['id'],
        'name': value['name'],
        'original_language': value['original_language'],
        'original_name': value['original_name'],
        'overview': value['overview'],
        'poster_path': value['poster_path'],
        'media_type': value['media_type'],
        'genre_ids': value['genre_ids'],
        'popularity': value['popularity'],
        'first_air_date': value['first_air_date'],
        'vote_average': value['vote_average'],
        'vote_count': value['vote_count'],
        'origin_country': value['origin_country'],
        'character': value['character'],
        'episodes': value['episodes'],
        'seasons': value['seasons'] == null ? undefined : ((value['seasons'] as Array<any>).map(CreditDetails200ResponseMediaSeasonsInnerToJSON)),
    };
}

