/* tslint:disable */
/* eslint-disable */
/**
 * TMDB API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreditDetails200ResponseMediaSeasonsInner
 */
export interface CreditDetails200ResponseMediaSeasonsInner {
    /**
     * 
     * @type {string}
     * @memberof CreditDetails200ResponseMediaSeasonsInner
     */
    air_date?: string;
    /**
     * 
     * @type {number}
     * @memberof CreditDetails200ResponseMediaSeasonsInner
     */
    episode_count?: number;
    /**
     * 
     * @type {number}
     * @memberof CreditDetails200ResponseMediaSeasonsInner
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof CreditDetails200ResponseMediaSeasonsInner
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof CreditDetails200ResponseMediaSeasonsInner
     */
    overview?: string;
    /**
     * 
     * @type {string}
     * @memberof CreditDetails200ResponseMediaSeasonsInner
     */
    poster_path?: string;
    /**
     * 
     * @type {number}
     * @memberof CreditDetails200ResponseMediaSeasonsInner
     */
    season_number?: number;
    /**
     * 
     * @type {number}
     * @memberof CreditDetails200ResponseMediaSeasonsInner
     */
    show_id?: number;
}

/**
 * Check if a given object implements the CreditDetails200ResponseMediaSeasonsInner interface.
 */
export function instanceOfCreditDetails200ResponseMediaSeasonsInner(value: object): value is CreditDetails200ResponseMediaSeasonsInner {
    return true;
}

export function CreditDetails200ResponseMediaSeasonsInnerFromJSON(json: any): CreditDetails200ResponseMediaSeasonsInner {
    return CreditDetails200ResponseMediaSeasonsInnerFromJSONTyped(json, false);
}

export function CreditDetails200ResponseMediaSeasonsInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreditDetails200ResponseMediaSeasonsInner {
    if (json == null) {
        return json;
    }
    return {
        
        'air_date': json['air_date'] == null ? undefined : json['air_date'],
        'episode_count': json['episode_count'] == null ? undefined : json['episode_count'],
        'id': json['id'] == null ? undefined : json['id'],
        'name': json['name'] == null ? undefined : json['name'],
        'overview': json['overview'] == null ? undefined : json['overview'],
        'poster_path': json['poster_path'] == null ? undefined : json['poster_path'],
        'season_number': json['season_number'] == null ? undefined : json['season_number'],
        'show_id': json['show_id'] == null ? undefined : json['show_id'],
    };
}

export function CreditDetails200ResponseMediaSeasonsInnerToJSON(value?: CreditDetails200ResponseMediaSeasonsInner | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'air_date': value['air_date'],
        'episode_count': value['episode_count'],
        'id': value['id'],
        'name': value['name'],
        'overview': value['overview'],
        'poster_path': value['poster_path'],
        'season_number': value['season_number'],
        'show_id': value['show_id'],
    };
}

