/* tslint:disable */
/* eslint-disable */
/**
 * TMDB API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { DiscoverMovie200ResponseResultsInner } from './DiscoverMovie200ResponseResultsInner';
import {
    DiscoverMovie200ResponseResultsInnerFromJSON,
    DiscoverMovie200ResponseResultsInnerFromJSONTyped,
    DiscoverMovie200ResponseResultsInnerToJSON,
} from './DiscoverMovie200ResponseResultsInner';

/**
 * 
 * @export
 * @interface DiscoverMovie200Response
 */
export interface DiscoverMovie200Response {
    /**
     * 
     * @type {number}
     * @memberof DiscoverMovie200Response
     */
    page?: number;
    /**
     * 
     * @type {Array<DiscoverMovie200ResponseResultsInner>}
     * @memberof DiscoverMovie200Response
     */
    results?: Array<DiscoverMovie200ResponseResultsInner>;
    /**
     * 
     * @type {number}
     * @memberof DiscoverMovie200Response
     */
    total_pages?: number;
    /**
     * 
     * @type {number}
     * @memberof DiscoverMovie200Response
     */
    total_results?: number;
}

/**
 * Check if a given object implements the DiscoverMovie200Response interface.
 */
export function instanceOfDiscoverMovie200Response(value: object): value is DiscoverMovie200Response {
    return true;
}

export function DiscoverMovie200ResponseFromJSON(json: any): DiscoverMovie200Response {
    return DiscoverMovie200ResponseFromJSONTyped(json, false);
}

export function DiscoverMovie200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): DiscoverMovie200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'page': json['page'] == null ? undefined : json['page'],
        'results': json['results'] == null ? undefined : ((json['results'] as Array<any>).map(DiscoverMovie200ResponseResultsInnerFromJSON)),
        'total_pages': json['total_pages'] == null ? undefined : json['total_pages'],
        'total_results': json['total_results'] == null ? undefined : json['total_results'],
    };
}

export function DiscoverMovie200ResponseToJSON(value?: DiscoverMovie200Response | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'page': value['page'],
        'results': value['results'] == null ? undefined : ((value['results'] as Array<any>).map(DiscoverMovie200ResponseResultsInnerToJSON)),
        'total_pages': value['total_pages'],
        'total_results': value['total_results'],
    };
}

