/* tslint:disable */
/* eslint-disable */
/**
 * TMDB API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { FindById200ResponseMovieResultsInner } from './FindById200ResponseMovieResultsInner';
import {
    FindById200ResponseMovieResultsInnerFromJSON,
    FindById200ResponseMovieResultsInnerFromJSONTyped,
    FindById200ResponseMovieResultsInnerToJSON,
} from './FindById200ResponseMovieResultsInner';

/**
 * 
 * @export
 * @interface FindById200Response
 */
export interface FindById200Response {
    /**
     * 
     * @type {Array<FindById200ResponseMovieResultsInner>}
     * @memberof FindById200Response
     */
    movie_results?: Array<FindById200ResponseMovieResultsInner>;
    /**
     * 
     * @type {Array<string>}
     * @memberof FindById200Response
     */
    person_results?: Array<string>;
    /**
     * 
     * @type {Array<string>}
     * @memberof FindById200Response
     */
    tv_results?: Array<string>;
    /**
     * 
     * @type {Array<string>}
     * @memberof FindById200Response
     */
    tv_episode_results?: Array<string>;
    /**
     * 
     * @type {Array<string>}
     * @memberof FindById200Response
     */
    tv_season_results?: Array<string>;
}

/**
 * Check if a given object implements the FindById200Response interface.
 */
export function instanceOfFindById200Response(value: object): value is FindById200Response {
    return true;
}

export function FindById200ResponseFromJSON(json: any): FindById200Response {
    return FindById200ResponseFromJSONTyped(json, false);
}

export function FindById200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): FindById200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'movie_results': json['movie_results'] == null ? undefined : ((json['movie_results'] as Array<any>).map(FindById200ResponseMovieResultsInnerFromJSON)),
        'person_results': json['person_results'] == null ? undefined : json['person_results'],
        'tv_results': json['tv_results'] == null ? undefined : json['tv_results'],
        'tv_episode_results': json['tv_episode_results'] == null ? undefined : json['tv_episode_results'],
        'tv_season_results': json['tv_season_results'] == null ? undefined : json['tv_season_results'],
    };
}

export function FindById200ResponseToJSON(value?: FindById200Response | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'movie_results': value['movie_results'] == null ? undefined : ((value['movie_results'] as Array<any>).map(FindById200ResponseMovieResultsInnerToJSON)),
        'person_results': value['person_results'],
        'tv_results': value['tv_results'],
        'tv_episode_results': value['tv_episode_results'],
        'tv_season_results': value['tv_season_results'],
    };
}

