/* tslint:disable */
/* eslint-disable */
/**
 * TMDB API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { GuestSessionRatedMovies200ResponseResultsInner } from './GuestSessionRatedMovies200ResponseResultsInner';
import {
    GuestSessionRatedMovies200ResponseResultsInnerFromJSON,
    GuestSessionRatedMovies200ResponseResultsInnerFromJSONTyped,
    GuestSessionRatedMovies200ResponseResultsInnerToJSON,
} from './GuestSessionRatedMovies200ResponseResultsInner';

/**
 * 
 * @export
 * @interface GuestSessionRatedMovies200Response
 */
export interface GuestSessionRatedMovies200Response {
    /**
     * 
     * @type {number}
     * @memberof GuestSessionRatedMovies200Response
     */
    page?: number;
    /**
     * 
     * @type {Array<GuestSessionRatedMovies200ResponseResultsInner>}
     * @memberof GuestSessionRatedMovies200Response
     */
    results?: Array<GuestSessionRatedMovies200ResponseResultsInner>;
    /**
     * 
     * @type {number}
     * @memberof GuestSessionRatedMovies200Response
     */
    total_pages?: number;
    /**
     * 
     * @type {number}
     * @memberof GuestSessionRatedMovies200Response
     */
    total_results?: number;
}

/**
 * Check if a given object implements the GuestSessionRatedMovies200Response interface.
 */
export function instanceOfGuestSessionRatedMovies200Response(value: object): value is GuestSessionRatedMovies200Response {
    return true;
}

export function GuestSessionRatedMovies200ResponseFromJSON(json: any): GuestSessionRatedMovies200Response {
    return GuestSessionRatedMovies200ResponseFromJSONTyped(json, false);
}

export function GuestSessionRatedMovies200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GuestSessionRatedMovies200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'page': json['page'] == null ? undefined : json['page'],
        'results': json['results'] == null ? undefined : ((json['results'] as Array<any>).map(GuestSessionRatedMovies200ResponseResultsInnerFromJSON)),
        'total_pages': json['total_pages'] == null ? undefined : json['total_pages'],
        'total_results': json['total_results'] == null ? undefined : json['total_results'],
    };
}

export function GuestSessionRatedMovies200ResponseToJSON(value?: GuestSessionRatedMovies200Response | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'page': value['page'],
        'results': value['results'] == null ? undefined : ((value['results'] as Array<any>).map(GuestSessionRatedMovies200ResponseResultsInnerToJSON)),
        'total_pages': value['total_pages'],
        'total_results': value['total_results'],
    };
}

