/* tslint:disable */
/* eslint-disable */
/**
 * TMDB API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ListDetails200ResponseItemsInner } from './ListDetails200ResponseItemsInner';
import {
    ListDetails200ResponseItemsInnerFromJSON,
    ListDetails200ResponseItemsInnerFromJSONTyped,
    ListDetails200ResponseItemsInnerToJSON,
} from './ListDetails200ResponseItemsInner';

/**
 * 
 * @export
 * @interface ListDetails200Response
 */
export interface ListDetails200Response {
    /**
     * 
     * @type {string}
     * @memberof ListDetails200Response
     */
    created_by?: string;
    /**
     * 
     * @type {string}
     * @memberof ListDetails200Response
     */
    description?: string;
    /**
     * 
     * @type {number}
     * @memberof ListDetails200Response
     */
    favorite_count?: number;
    /**
     * 
     * @type {string}
     * @memberof ListDetails200Response
     */
    id?: string;
    /**
     * 
     * @type {Array<ListDetails200ResponseItemsInner>}
     * @memberof ListDetails200Response
     */
    items?: Array<ListDetails200ResponseItemsInner>;
    /**
     * 
     * @type {number}
     * @memberof ListDetails200Response
     */
    item_count?: number;
    /**
     * 
     * @type {string}
     * @memberof ListDetails200Response
     */
    iso_639_1?: string;
    /**
     * 
     * @type {string}
     * @memberof ListDetails200Response
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof ListDetails200Response
     */
    poster_path?: string;
}

/**
 * Check if a given object implements the ListDetails200Response interface.
 */
export function instanceOfListDetails200Response(value: object): value is ListDetails200Response {
    return true;
}

export function ListDetails200ResponseFromJSON(json: any): ListDetails200Response {
    return ListDetails200ResponseFromJSONTyped(json, false);
}

export function ListDetails200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ListDetails200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'created_by': json['created_by'] == null ? undefined : json['created_by'],
        'description': json['description'] == null ? undefined : json['description'],
        'favorite_count': json['favorite_count'] == null ? undefined : json['favorite_count'],
        'id': json['id'] == null ? undefined : json['id'],
        'items': json['items'] == null ? undefined : ((json['items'] as Array<any>).map(ListDetails200ResponseItemsInnerFromJSON)),
        'item_count': json['item_count'] == null ? undefined : json['item_count'],
        'iso_639_1': json['iso_639_1'] == null ? undefined : json['iso_639_1'],
        'name': json['name'] == null ? undefined : json['name'],
        'poster_path': json['poster_path'] == null ? undefined : json['poster_path'],
    };
}

export function ListDetails200ResponseToJSON(value?: ListDetails200Response | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'created_by': value['created_by'],
        'description': value['description'],
        'favorite_count': value['favorite_count'],
        'id': value['id'],
        'items': value['items'] == null ? undefined : ((value['items'] as Array<any>).map(ListDetails200ResponseItemsInnerToJSON)),
        'item_count': value['item_count'],
        'iso_639_1': value['iso_639_1'],
        'name': value['name'],
        'poster_path': value['poster_path'],
    };
}

