/* tslint:disable */
/* eslint-disable */
/**
 * TMDB API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ListAddMovieRequest
 */
export interface ListAddMovieRequest {
    /**
     * 
     * @type {string}
     * @memberof ListAddMovieRequest
     */
    RAW_BODY?: string;
}

/**
 * Check if a given object implements the ListAddMovieRequest interface.
 */
export function instanceOfListAddMovieRequest(value: object): value is ListAddMovieRequest {
    return true;
}

export function ListAddMovieRequestFromJSON(json: any): ListAddMovieRequest {
    return ListAddMovieRequestFromJSONTyped(json, false);
}

export function ListAddMovieRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): ListAddMovieRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'RAW_BODY': json['RAW_BODY'] == null ? undefined : json['RAW_BODY'],
    };
}

export function ListAddMovieRequestToJSON(value?: ListAddMovieRequest | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'RAW_BODY': value['RAW_BODY'],
    };
}

