/* tslint:disable */
/* eslint-disable */
/**
 * TMDB API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface MovieReleaseDates200ResponseResultsInnerReleaseDatesInner
 */
export interface MovieReleaseDates200ResponseResultsInnerReleaseDatesInner {
    /**
     * 
     * @type {string}
     * @memberof MovieReleaseDates200ResponseResultsInnerReleaseDatesInner
     */
    certification?: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof MovieReleaseDates200ResponseResultsInnerReleaseDatesInner
     */
    descriptors?: Array<string>;
    /**
     * 
     * @type {string}
     * @memberof MovieReleaseDates200ResponseResultsInnerReleaseDatesInner
     */
    iso_639_1?: string;
    /**
     * 
     * @type {string}
     * @memberof MovieReleaseDates200ResponseResultsInnerReleaseDatesInner
     */
    note?: string;
    /**
     * 
     * @type {string}
     * @memberof MovieReleaseDates200ResponseResultsInnerReleaseDatesInner
     */
    release_date?: string;
    /**
     * 
     * @type {number}
     * @memberof MovieReleaseDates200ResponseResultsInnerReleaseDatesInner
     */
    type?: number;
}

/**
 * Check if a given object implements the MovieReleaseDates200ResponseResultsInnerReleaseDatesInner interface.
 */
export function instanceOfMovieReleaseDates200ResponseResultsInnerReleaseDatesInner(value: object): value is MovieReleaseDates200ResponseResultsInnerReleaseDatesInner {
    return true;
}

export function MovieReleaseDates200ResponseResultsInnerReleaseDatesInnerFromJSON(json: any): MovieReleaseDates200ResponseResultsInnerReleaseDatesInner {
    return MovieReleaseDates200ResponseResultsInnerReleaseDatesInnerFromJSONTyped(json, false);
}

export function MovieReleaseDates200ResponseResultsInnerReleaseDatesInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): MovieReleaseDates200ResponseResultsInnerReleaseDatesInner {
    if (json == null) {
        return json;
    }
    return {
        
        'certification': json['certification'] == null ? undefined : json['certification'],
        'descriptors': json['descriptors'] == null ? undefined : json['descriptors'],
        'iso_639_1': json['iso_639_1'] == null ? undefined : json['iso_639_1'],
        'note': json['note'] == null ? undefined : json['note'],
        'release_date': json['release_date'] == null ? undefined : json['release_date'],
        'type': json['type'] == null ? undefined : json['type'],
    };
}

export function MovieReleaseDates200ResponseResultsInnerReleaseDatesInnerToJSON(value?: MovieReleaseDates200ResponseResultsInnerReleaseDatesInner | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'certification': value['certification'],
        'descriptors': value['descriptors'],
        'iso_639_1': value['iso_639_1'],
        'note': value['note'],
        'release_date': value['release_date'],
        'type': value['type'],
    };
}

