/* tslint:disable */
/* eslint-disable */
/**
 * TMDB API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface MovieAddRating200Response
 */
export interface MovieAddRating200Response {
    /**
     * 
     * @type {number}
     * @memberof MovieAddRating200Response
     */
    status_code?: number;
    /**
     * 
     * @type {string}
     * @memberof MovieAddRating200Response
     */
    status_message?: string;
}

/**
 * Check if a given object implements the MovieAddRating200Response interface.
 */
export function instanceOfMovieAddRating200Response(value: object): value is MovieAddRating200Response {
    return true;
}

export function MovieAddRating200ResponseFromJSON(json: any): MovieAddRating200Response {
    return MovieAddRating200ResponseFromJSONTyped(json, false);
}

export function MovieAddRating200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): MovieAddRating200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'status_code': json['status_code'] == null ? undefined : json['status_code'],
        'status_message': json['status_message'] == null ? undefined : json['status_message'],
    };
}

export function MovieAddRating200ResponseToJSON(value?: MovieAddRating200Response | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'status_code': value['status_code'],
        'status_message': value['status_message'],
    };
}

