/* tslint:disable */
/* eslint-disable */
/**
 * TMDB API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface MovieImages200ResponsePostersInner
 */
export interface MovieImages200ResponsePostersInner {
    /**
     * 
     * @type {number}
     * @memberof MovieImages200ResponsePostersInner
     */
    aspect_ratio?: number;
    /**
     * 
     * @type {number}
     * @memberof MovieImages200ResponsePostersInner
     */
    height?: number;
    /**
     * 
     * @type {string}
     * @memberof MovieImages200ResponsePostersInner
     */
    iso_639_1?: string;
    /**
     * 
     * @type {string}
     * @memberof MovieImages200ResponsePostersInner
     */
    file_path?: string;
    /**
     * 
     * @type {number}
     * @memberof MovieImages200ResponsePostersInner
     */
    vote_average?: number;
    /**
     * 
     * @type {number}
     * @memberof MovieImages200ResponsePostersInner
     */
    vote_count?: number;
    /**
     * 
     * @type {number}
     * @memberof MovieImages200ResponsePostersInner
     */
    width?: number;
}

/**
 * Check if a given object implements the MovieImages200ResponsePostersInner interface.
 */
export function instanceOfMovieImages200ResponsePostersInner(value: object): value is MovieImages200ResponsePostersInner {
    return true;
}

export function MovieImages200ResponsePostersInnerFromJSON(json: any): MovieImages200ResponsePostersInner {
    return MovieImages200ResponsePostersInnerFromJSONTyped(json, false);
}

export function MovieImages200ResponsePostersInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): MovieImages200ResponsePostersInner {
    if (json == null) {
        return json;
    }
    return {
        
        'aspect_ratio': json['aspect_ratio'] == null ? undefined : json['aspect_ratio'],
        'height': json['height'] == null ? undefined : json['height'],
        'iso_639_1': json['iso_639_1'] == null ? undefined : json['iso_639_1'],
        'file_path': json['file_path'] == null ? undefined : json['file_path'],
        'vote_average': json['vote_average'] == null ? undefined : json['vote_average'],
        'vote_count': json['vote_count'] == null ? undefined : json['vote_count'],
        'width': json['width'] == null ? undefined : json['width'],
    };
}

export function MovieImages200ResponsePostersInnerToJSON(value?: MovieImages200ResponsePostersInner | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'aspect_ratio': value['aspect_ratio'],
        'height': value['height'],
        'iso_639_1': value['iso_639_1'],
        'file_path': value['file_path'],
        'vote_average': value['vote_average'],
        'vote_count': value['vote_count'],
        'width': value['width'],
    };
}

