/* tslint:disable */
/* eslint-disable */
/**
 * TMDB API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { MovieSimilar200ResponseResultsInner } from './MovieSimilar200ResponseResultsInner';
import {
    MovieSimilar200ResponseResultsInnerFromJSON,
    MovieSimilar200ResponseResultsInnerFromJSONTyped,
    MovieSimilar200ResponseResultsInnerToJSON,
} from './MovieSimilar200ResponseResultsInner';

/**
 * 
 * @export
 * @interface MovieSimilar200Response
 */
export interface MovieSimilar200Response {
    /**
     * 
     * @type {number}
     * @memberof MovieSimilar200Response
     */
    page?: number;
    /**
     * 
     * @type {Array<MovieSimilar200ResponseResultsInner>}
     * @memberof MovieSimilar200Response
     */
    results?: Array<MovieSimilar200ResponseResultsInner>;
    /**
     * 
     * @type {number}
     * @memberof MovieSimilar200Response
     */
    total_pages?: number;
    /**
     * 
     * @type {number}
     * @memberof MovieSimilar200Response
     */
    total_results?: number;
}

/**
 * Check if a given object implements the MovieSimilar200Response interface.
 */
export function instanceOfMovieSimilar200Response(value: object): value is MovieSimilar200Response {
    return true;
}

export function MovieSimilar200ResponseFromJSON(json: any): MovieSimilar200Response {
    return MovieSimilar200ResponseFromJSONTyped(json, false);
}

export function MovieSimilar200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): MovieSimilar200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'page': json['page'] == null ? undefined : json['page'],
        'results': json['results'] == null ? undefined : ((json['results'] as Array<any>).map(MovieSimilar200ResponseResultsInnerFromJSON)),
        'total_pages': json['total_pages'] == null ? undefined : json['total_pages'],
        'total_results': json['total_results'] == null ? undefined : json['total_results'],
    };
}

export function MovieSimilar200ResponseToJSON(value?: MovieSimilar200Response | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'page': value['page'],
        'results': value['results'] == null ? undefined : ((value['results'] as Array<any>).map(MovieSimilar200ResponseResultsInnerToJSON)),
        'total_pages': value['total_pages'],
        'total_results': value['total_results'],
    };
}

