/* tslint:disable */
/* eslint-disable */
/**
 * TMDB API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface MovieChanges200ResponseChangesInnerItemsInnerValuePoster
 */
export interface MovieChanges200ResponseChangesInnerItemsInnerValuePoster {
    /**
     * 
     * @type {string}
     * @memberof MovieChanges200ResponseChangesInnerItemsInnerValuePoster
     */
    file_path?: string;
}

/**
 * Check if a given object implements the MovieChanges200ResponseChangesInnerItemsInnerValuePoster interface.
 */
export function instanceOfMovieChanges200ResponseChangesInnerItemsInnerValuePoster(value: object): value is MovieChanges200ResponseChangesInnerItemsInnerValuePoster {
    return true;
}

export function MovieChanges200ResponseChangesInnerItemsInnerValuePosterFromJSON(json: any): MovieChanges200ResponseChangesInnerItemsInnerValuePoster {
    return MovieChanges200ResponseChangesInnerItemsInnerValuePosterFromJSONTyped(json, false);
}

export function MovieChanges200ResponseChangesInnerItemsInnerValuePosterFromJSONTyped(json: any, ignoreDiscriminator: boolean): MovieChanges200ResponseChangesInnerItemsInnerValuePoster {
    if (json == null) {
        return json;
    }
    return {
        
        'file_path': json['file_path'] == null ? undefined : json['file_path'],
    };
}

export function MovieChanges200ResponseChangesInnerItemsInnerValuePosterToJSON(value?: MovieChanges200ResponseChangesInnerItemsInnerValuePoster | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'file_path': value['file_path'],
    };
}

