/* tslint:disable */
/* eslint-disable */
/**
 * TMDB API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface MovieReviews200ResponseResultsInnerAuthorDetails
 */
export interface MovieReviews200ResponseResultsInnerAuthorDetails {
    /**
     * 
     * @type {string}
     * @memberof MovieReviews200ResponseResultsInnerAuthorDetails
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof MovieReviews200ResponseResultsInnerAuthorDetails
     */
    username?: string;
    /**
     * 
     * @type {string}
     * @memberof MovieReviews200ResponseResultsInnerAuthorDetails
     */
    avatar_path?: string;
    /**
     * 
     * @type {any}
     * @memberof MovieReviews200ResponseResultsInnerAuthorDetails
     */
    rating?: any;
}

/**
 * Check if a given object implements the MovieReviews200ResponseResultsInnerAuthorDetails interface.
 */
export function instanceOfMovieReviews200ResponseResultsInnerAuthorDetails(value: object): value is MovieReviews200ResponseResultsInnerAuthorDetails {
    return true;
}

export function MovieReviews200ResponseResultsInnerAuthorDetailsFromJSON(json: any): MovieReviews200ResponseResultsInnerAuthorDetails {
    return MovieReviews200ResponseResultsInnerAuthorDetailsFromJSONTyped(json, false);
}

export function MovieReviews200ResponseResultsInnerAuthorDetailsFromJSONTyped(json: any, ignoreDiscriminator: boolean): MovieReviews200ResponseResultsInnerAuthorDetails {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'] == null ? undefined : json['name'],
        'username': json['username'] == null ? undefined : json['username'],
        'avatar_path': json['avatar_path'] == null ? undefined : json['avatar_path'],
        'rating': json['rating'] == null ? undefined : json['rating'],
    };
}

export function MovieReviews200ResponseResultsInnerAuthorDetailsToJSON(value?: MovieReviews200ResponseResultsInnerAuthorDetails | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'name': value['name'],
        'username': value['username'],
        'avatar_path': value['avatar_path'],
        'rating': value['rating'],
    };
}

