/* tslint:disable */
/* eslint-disable */
/**
 * TMDB API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { MovieReleaseDates200ResponseResultsInnerReleaseDatesInner } from './MovieReleaseDates200ResponseResultsInnerReleaseDatesInner';
import {
    MovieReleaseDates200ResponseResultsInnerReleaseDatesInnerFromJSON,
    MovieReleaseDates200ResponseResultsInnerReleaseDatesInnerFromJSONTyped,
    MovieReleaseDates200ResponseResultsInnerReleaseDatesInnerToJSON,
} from './MovieReleaseDates200ResponseResultsInnerReleaseDatesInner';

/**
 * 
 * @export
 * @interface MovieReleaseDates200ResponseResultsInner
 */
export interface MovieReleaseDates200ResponseResultsInner {
    /**
     * 
     * @type {string}
     * @memberof MovieReleaseDates200ResponseResultsInner
     */
    iso_3166_1?: string;
    /**
     * 
     * @type {Array<MovieReleaseDates200ResponseResultsInnerReleaseDatesInner>}
     * @memberof MovieReleaseDates200ResponseResultsInner
     */
    release_dates?: Array<MovieReleaseDates200ResponseResultsInnerReleaseDatesInner>;
}

/**
 * Check if a given object implements the MovieReleaseDates200ResponseResultsInner interface.
 */
export function instanceOfMovieReleaseDates200ResponseResultsInner(value: object): value is MovieReleaseDates200ResponseResultsInner {
    return true;
}

export function MovieReleaseDates200ResponseResultsInnerFromJSON(json: any): MovieReleaseDates200ResponseResultsInner {
    return MovieReleaseDates200ResponseResultsInnerFromJSONTyped(json, false);
}

export function MovieReleaseDates200ResponseResultsInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): MovieReleaseDates200ResponseResultsInner {
    if (json == null) {
        return json;
    }
    return {
        
        'iso_3166_1': json['iso_3166_1'] == null ? undefined : json['iso_3166_1'],
        'release_dates': json['release_dates'] == null ? undefined : ((json['release_dates'] as Array<any>).map(MovieReleaseDates200ResponseResultsInnerReleaseDatesInnerFromJSON)),
    };
}

export function MovieReleaseDates200ResponseResultsInnerToJSON(value?: MovieReleaseDates200ResponseResultsInner | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'iso_3166_1': value['iso_3166_1'],
        'release_dates': value['release_dates'] == null ? undefined : ((value['release_dates'] as Array<any>).map(MovieReleaseDates200ResponseResultsInnerReleaseDatesInnerToJSON)),
    };
}

