/* tslint:disable */
/* eslint-disable */
/**
 * TMDB API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface MovieDeleteRating200Response
 */
export interface MovieDeleteRating200Response {
    /**
     * 
     * @type {number}
     * @memberof MovieDeleteRating200Response
     */
    status_code?: number;
    /**
     * 
     * @type {string}
     * @memberof MovieDeleteRating200Response
     */
    status_message?: string;
}

/**
 * Check if a given object implements the MovieDeleteRating200Response interface.
 */
export function instanceOfMovieDeleteRating200Response(value: object): value is MovieDeleteRating200Response {
    return true;
}

export function MovieDeleteRating200ResponseFromJSON(json: any): MovieDeleteRating200Response {
    return MovieDeleteRating200ResponseFromJSONTyped(json, false);
}

export function MovieDeleteRating200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): MovieDeleteRating200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'status_code': json['status_code'] == null ? undefined : json['status_code'],
        'status_message': json['status_message'] == null ? undefined : json['status_message'],
    };
}

export function MovieDeleteRating200ResponseToJSON(value?: MovieDeleteRating200Response | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'status_code': value['status_code'],
        'status_message': value['status_message'],
    };
}

