/* tslint:disable */
/* eslint-disable */
/**
 * TMDB API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PersonPopularList200ResponseResultsInnerKnownForInner
 */
export interface PersonPopularList200ResponseResultsInnerKnownForInner {
    /**
     * 
     * @type {boolean}
     * @memberof PersonPopularList200ResponseResultsInnerKnownForInner
     */
    adult?: boolean;
    /**
     * 
     * @type {string}
     * @memberof PersonPopularList200ResponseResultsInnerKnownForInner
     */
    backdrop_path?: string;
    /**
     * 
     * @type {Array<number>}
     * @memberof PersonPopularList200ResponseResultsInnerKnownForInner
     */
    genre_ids?: Array<number>;
    /**
     * 
     * @type {number}
     * @memberof PersonPopularList200ResponseResultsInnerKnownForInner
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof PersonPopularList200ResponseResultsInnerKnownForInner
     */
    media_type?: string;
    /**
     * 
     * @type {string}
     * @memberof PersonPopularList200ResponseResultsInnerKnownForInner
     */
    original_language?: string;
    /**
     * 
     * @type {string}
     * @memberof PersonPopularList200ResponseResultsInnerKnownForInner
     */
    original_title?: string;
    /**
     * 
     * @type {string}
     * @memberof PersonPopularList200ResponseResultsInnerKnownForInner
     */
    overview?: string;
    /**
     * 
     * @type {string}
     * @memberof PersonPopularList200ResponseResultsInnerKnownForInner
     */
    poster_path?: string;
    /**
     * 
     * @type {string}
     * @memberof PersonPopularList200ResponseResultsInnerKnownForInner
     */
    release_date?: string;
    /**
     * 
     * @type {string}
     * @memberof PersonPopularList200ResponseResultsInnerKnownForInner
     */
    title?: string;
    /**
     * 
     * @type {boolean}
     * @memberof PersonPopularList200ResponseResultsInnerKnownForInner
     */
    video?: boolean;
    /**
     * 
     * @type {number}
     * @memberof PersonPopularList200ResponseResultsInnerKnownForInner
     */
    vote_average?: number;
    /**
     * 
     * @type {number}
     * @memberof PersonPopularList200ResponseResultsInnerKnownForInner
     */
    vote_count?: number;
}

/**
 * Check if a given object implements the PersonPopularList200ResponseResultsInnerKnownForInner interface.
 */
export function instanceOfPersonPopularList200ResponseResultsInnerKnownForInner(value: object): value is PersonPopularList200ResponseResultsInnerKnownForInner {
    return true;
}

export function PersonPopularList200ResponseResultsInnerKnownForInnerFromJSON(json: any): PersonPopularList200ResponseResultsInnerKnownForInner {
    return PersonPopularList200ResponseResultsInnerKnownForInnerFromJSONTyped(json, false);
}

export function PersonPopularList200ResponseResultsInnerKnownForInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): PersonPopularList200ResponseResultsInnerKnownForInner {
    if (json == null) {
        return json;
    }
    return {
        
        'adult': json['adult'] == null ? undefined : json['adult'],
        'backdrop_path': json['backdrop_path'] == null ? undefined : json['backdrop_path'],
        'genre_ids': json['genre_ids'] == null ? undefined : json['genre_ids'],
        'id': json['id'] == null ? undefined : json['id'],
        'media_type': json['media_type'] == null ? undefined : json['media_type'],
        'original_language': json['original_language'] == null ? undefined : json['original_language'],
        'original_title': json['original_title'] == null ? undefined : json['original_title'],
        'overview': json['overview'] == null ? undefined : json['overview'],
        'poster_path': json['poster_path'] == null ? undefined : json['poster_path'],
        'release_date': json['release_date'] == null ? undefined : json['release_date'],
        'title': json['title'] == null ? undefined : json['title'],
        'video': json['video'] == null ? undefined : json['video'],
        'vote_average': json['vote_average'] == null ? undefined : json['vote_average'],
        'vote_count': json['vote_count'] == null ? undefined : json['vote_count'],
    };
}

export function PersonPopularList200ResponseResultsInnerKnownForInnerToJSON(value?: PersonPopularList200ResponseResultsInnerKnownForInner | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'adult': value['adult'],
        'backdrop_path': value['backdrop_path'],
        'genre_ids': value['genre_ids'],
        'id': value['id'],
        'media_type': value['media_type'],
        'original_language': value['original_language'],
        'original_title': value['original_title'],
        'overview': value['overview'],
        'poster_path': value['poster_path'],
        'release_date': value['release_date'],
        'title': value['title'],
        'video': value['video'],
        'vote_average': value['vote_average'],
        'vote_count': value['vote_count'],
    };
}

