/* tslint:disable */
/* eslint-disable */
/**
 * TMDB API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PersonTaggedImages200ResponseResultsInnerMedia } from './PersonTaggedImages200ResponseResultsInnerMedia';
import {
    PersonTaggedImages200ResponseResultsInnerMediaFromJSON,
    PersonTaggedImages200ResponseResultsInnerMediaFromJSONTyped,
    PersonTaggedImages200ResponseResultsInnerMediaToJSON,
} from './PersonTaggedImages200ResponseResultsInnerMedia';

/**
 * 
 * @export
 * @interface PersonTaggedImages200ResponseResultsInner
 */
export interface PersonTaggedImages200ResponseResultsInner {
    /**
     * 
     * @type {number}
     * @memberof PersonTaggedImages200ResponseResultsInner
     */
    aspect_ratio?: number;
    /**
     * 
     * @type {string}
     * @memberof PersonTaggedImages200ResponseResultsInner
     */
    file_path?: string;
    /**
     * 
     * @type {number}
     * @memberof PersonTaggedImages200ResponseResultsInner
     */
    height?: number;
    /**
     * 
     * @type {string}
     * @memberof PersonTaggedImages200ResponseResultsInner
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof PersonTaggedImages200ResponseResultsInner
     */
    iso_639_1?: string;
    /**
     * 
     * @type {number}
     * @memberof PersonTaggedImages200ResponseResultsInner
     */
    vote_average?: number;
    /**
     * 
     * @type {number}
     * @memberof PersonTaggedImages200ResponseResultsInner
     */
    vote_count?: number;
    /**
     * 
     * @type {number}
     * @memberof PersonTaggedImages200ResponseResultsInner
     */
    width?: number;
    /**
     * 
     * @type {string}
     * @memberof PersonTaggedImages200ResponseResultsInner
     */
    image_type?: string;
    /**
     * 
     * @type {PersonTaggedImages200ResponseResultsInnerMedia}
     * @memberof PersonTaggedImages200ResponseResultsInner
     */
    media?: PersonTaggedImages200ResponseResultsInnerMedia;
    /**
     * 
     * @type {string}
     * @memberof PersonTaggedImages200ResponseResultsInner
     */
    media_type?: string;
}

/**
 * Check if a given object implements the PersonTaggedImages200ResponseResultsInner interface.
 */
export function instanceOfPersonTaggedImages200ResponseResultsInner(value: object): value is PersonTaggedImages200ResponseResultsInner {
    return true;
}

export function PersonTaggedImages200ResponseResultsInnerFromJSON(json: any): PersonTaggedImages200ResponseResultsInner {
    return PersonTaggedImages200ResponseResultsInnerFromJSONTyped(json, false);
}

export function PersonTaggedImages200ResponseResultsInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): PersonTaggedImages200ResponseResultsInner {
    if (json == null) {
        return json;
    }
    return {
        
        'aspect_ratio': json['aspect_ratio'] == null ? undefined : json['aspect_ratio'],
        'file_path': json['file_path'] == null ? undefined : json['file_path'],
        'height': json['height'] == null ? undefined : json['height'],
        'id': json['id'] == null ? undefined : json['id'],
        'iso_639_1': json['iso_639_1'] == null ? undefined : json['iso_639_1'],
        'vote_average': json['vote_average'] == null ? undefined : json['vote_average'],
        'vote_count': json['vote_count'] == null ? undefined : json['vote_count'],
        'width': json['width'] == null ? undefined : json['width'],
        'image_type': json['image_type'] == null ? undefined : json['image_type'],
        'media': json['media'] == null ? undefined : PersonTaggedImages200ResponseResultsInnerMediaFromJSON(json['media']),
        'media_type': json['media_type'] == null ? undefined : json['media_type'],
    };
}

export function PersonTaggedImages200ResponseResultsInnerToJSON(value?: PersonTaggedImages200ResponseResultsInner | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'aspect_ratio': value['aspect_ratio'],
        'file_path': value['file_path'],
        'height': value['height'],
        'id': value['id'],
        'iso_639_1': value['iso_639_1'],
        'vote_average': value['vote_average'],
        'vote_count': value['vote_count'],
        'width': value['width'],
        'image_type': value['image_type'],
        'media': PersonTaggedImages200ResponseResultsInnerMediaToJSON(value['media']),
        'media_type': value['media_type'],
    };
}

