/* tslint:disable */
/* eslint-disable */
/**
 * TMDB API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PersonLatestId200Response
 */
export interface PersonLatestId200Response {
    /**
     * 
     * @type {boolean}
     * @memberof PersonLatestId200Response
     */
    adult?: boolean;
    /**
     * 
     * @type {Array<string>}
     * @memberof PersonLatestId200Response
     */
    also_known_as?: Array<string>;
    /**
     * 
     * @type {string}
     * @memberof PersonLatestId200Response
     */
    biography?: string;
    /**
     * 
     * @type {any}
     * @memberof PersonLatestId200Response
     */
    birthday?: any;
    /**
     * 
     * @type {any}
     * @memberof PersonLatestId200Response
     */
    deathday?: any;
    /**
     * 
     * @type {number}
     * @memberof PersonLatestId200Response
     */
    gender?: number;
    /**
     * 
     * @type {any}
     * @memberof PersonLatestId200Response
     */
    homepage?: any;
    /**
     * 
     * @type {number}
     * @memberof PersonLatestId200Response
     */
    id?: number;
    /**
     * 
     * @type {any}
     * @memberof PersonLatestId200Response
     */
    imdb_id?: any;
    /**
     * 
     * @type {any}
     * @memberof PersonLatestId200Response
     */
    known_for_department?: any;
    /**
     * 
     * @type {string}
     * @memberof PersonLatestId200Response
     */
    name?: string;
    /**
     * 
     * @type {any}
     * @memberof PersonLatestId200Response
     */
    place_of_birth?: any;
    /**
     * 
     * @type {number}
     * @memberof PersonLatestId200Response
     */
    popularity?: number;
    /**
     * 
     * @type {any}
     * @memberof PersonLatestId200Response
     */
    profile_path?: any;
}

/**
 * Check if a given object implements the PersonLatestId200Response interface.
 */
export function instanceOfPersonLatestId200Response(value: object): value is PersonLatestId200Response {
    return true;
}

export function PersonLatestId200ResponseFromJSON(json: any): PersonLatestId200Response {
    return PersonLatestId200ResponseFromJSONTyped(json, false);
}

export function PersonLatestId200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): PersonLatestId200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'adult': json['adult'] == null ? undefined : json['adult'],
        'also_known_as': json['also_known_as'] == null ? undefined : json['also_known_as'],
        'biography': json['biography'] == null ? undefined : json['biography'],
        'birthday': json['birthday'] == null ? undefined : json['birthday'],
        'deathday': json['deathday'] == null ? undefined : json['deathday'],
        'gender': json['gender'] == null ? undefined : json['gender'],
        'homepage': json['homepage'] == null ? undefined : json['homepage'],
        'id': json['id'] == null ? undefined : json['id'],
        'imdb_id': json['imdb_id'] == null ? undefined : json['imdb_id'],
        'known_for_department': json['known_for_department'] == null ? undefined : json['known_for_department'],
        'name': json['name'] == null ? undefined : json['name'],
        'place_of_birth': json['place_of_birth'] == null ? undefined : json['place_of_birth'],
        'popularity': json['popularity'] == null ? undefined : json['popularity'],
        'profile_path': json['profile_path'] == null ? undefined : json['profile_path'],
    };
}

export function PersonLatestId200ResponseToJSON(value?: PersonLatestId200Response | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'adult': value['adult'],
        'also_known_as': value['also_known_as'],
        'biography': value['biography'],
        'birthday': value['birthday'],
        'deathday': value['deathday'],
        'gender': value['gender'],
        'homepage': value['homepage'],
        'id': value['id'],
        'imdb_id': value['imdb_id'],
        'known_for_department': value['known_for_department'],
        'name': value['name'],
        'place_of_birth': value['place_of_birth'],
        'popularity': value['popularity'],
        'profile_path': value['profile_path'],
    };
}

