/* tslint:disable */
/* eslint-disable */
/**
 * TMDB API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ReviewDetails200ResponseAuthorDetails
 */
export interface ReviewDetails200ResponseAuthorDetails {
    /**
     * 
     * @type {string}
     * @memberof ReviewDetails200ResponseAuthorDetails
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof ReviewDetails200ResponseAuthorDetails
     */
    username?: string;
    /**
     * 
     * @type {string}
     * @memberof ReviewDetails200ResponseAuthorDetails
     */
    avatar_path?: string;
    /**
     * 
     * @type {number}
     * @memberof ReviewDetails200ResponseAuthorDetails
     */
    rating?: number;
}

/**
 * Check if a given object implements the ReviewDetails200ResponseAuthorDetails interface.
 */
export function instanceOfReviewDetails200ResponseAuthorDetails(value: object): value is ReviewDetails200ResponseAuthorDetails {
    return true;
}

export function ReviewDetails200ResponseAuthorDetailsFromJSON(json: any): ReviewDetails200ResponseAuthorDetails {
    return ReviewDetails200ResponseAuthorDetailsFromJSONTyped(json, false);
}

export function ReviewDetails200ResponseAuthorDetailsFromJSONTyped(json: any, ignoreDiscriminator: boolean): ReviewDetails200ResponseAuthorDetails {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'] == null ? undefined : json['name'],
        'username': json['username'] == null ? undefined : json['username'],
        'avatar_path': json['avatar_path'] == null ? undefined : json['avatar_path'],
        'rating': json['rating'] == null ? undefined : json['rating'],
    };
}

export function ReviewDetails200ResponseAuthorDetailsToJSON(value?: ReviewDetails200ResponseAuthorDetails | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'name': value['name'],
        'username': value['username'],
        'avatar_path': value['avatar_path'],
        'rating': value['rating'],
    };
}

