/* tslint:disable */
/* eslint-disable */
/**
 * TMDB API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SearchCollection200ResponseResultsInner
 */
export interface SearchCollection200ResponseResultsInner {
    /**
     * 
     * @type {boolean}
     * @memberof SearchCollection200ResponseResultsInner
     */
    adult?: boolean;
    /**
     * 
     * @type {string}
     * @memberof SearchCollection200ResponseResultsInner
     */
    backdrop_path?: string;
    /**
     * 
     * @type {number}
     * @memberof SearchCollection200ResponseResultsInner
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof SearchCollection200ResponseResultsInner
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof SearchCollection200ResponseResultsInner
     */
    original_language?: string;
    /**
     * 
     * @type {string}
     * @memberof SearchCollection200ResponseResultsInner
     */
    original_name?: string;
    /**
     * 
     * @type {string}
     * @memberof SearchCollection200ResponseResultsInner
     */
    overview?: string;
    /**
     * 
     * @type {string}
     * @memberof SearchCollection200ResponseResultsInner
     */
    poster_path?: string;
}

/**
 * Check if a given object implements the SearchCollection200ResponseResultsInner interface.
 */
export function instanceOfSearchCollection200ResponseResultsInner(value: object): value is SearchCollection200ResponseResultsInner {
    return true;
}

export function SearchCollection200ResponseResultsInnerFromJSON(json: any): SearchCollection200ResponseResultsInner {
    return SearchCollection200ResponseResultsInnerFromJSONTyped(json, false);
}

export function SearchCollection200ResponseResultsInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): SearchCollection200ResponseResultsInner {
    if (json == null) {
        return json;
    }
    return {
        
        'adult': json['adult'] == null ? undefined : json['adult'],
        'backdrop_path': json['backdrop_path'] == null ? undefined : json['backdrop_path'],
        'id': json['id'] == null ? undefined : json['id'],
        'name': json['name'] == null ? undefined : json['name'],
        'original_language': json['original_language'] == null ? undefined : json['original_language'],
        'original_name': json['original_name'] == null ? undefined : json['original_name'],
        'overview': json['overview'] == null ? undefined : json['overview'],
        'poster_path': json['poster_path'] == null ? undefined : json['poster_path'],
    };
}

export function SearchCollection200ResponseResultsInnerToJSON(value?: SearchCollection200ResponseResultsInner | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'adult': value['adult'],
        'backdrop_path': value['backdrop_path'],
        'id': value['id'],
        'name': value['name'],
        'original_language': value['original_language'],
        'original_name': value['original_name'],
        'overview': value['overview'],
        'poster_path': value['poster_path'],
    };
}

