/* tslint:disable */
/* eslint-disable */
/**
 * TMDB API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { SearchKeyword200ResponseResultsInner } from './SearchKeyword200ResponseResultsInner';
import {
    SearchKeyword200ResponseResultsInnerFromJSON,
    SearchKeyword200ResponseResultsInnerFromJSONTyped,
    SearchKeyword200ResponseResultsInnerToJSON,
} from './SearchKeyword200ResponseResultsInner';

/**
 * 
 * @export
 * @interface SearchKeyword200Response
 */
export interface SearchKeyword200Response {
    /**
     * 
     * @type {number}
     * @memberof SearchKeyword200Response
     */
    page?: number;
    /**
     * 
     * @type {Array<SearchKeyword200ResponseResultsInner>}
     * @memberof SearchKeyword200Response
     */
    results?: Array<SearchKeyword200ResponseResultsInner>;
    /**
     * 
     * @type {number}
     * @memberof SearchKeyword200Response
     */
    total_pages?: number;
    /**
     * 
     * @type {number}
     * @memberof SearchKeyword200Response
     */
    total_results?: number;
}

/**
 * Check if a given object implements the SearchKeyword200Response interface.
 */
export function instanceOfSearchKeyword200Response(value: object): value is SearchKeyword200Response {
    return true;
}

export function SearchKeyword200ResponseFromJSON(json: any): SearchKeyword200Response {
    return SearchKeyword200ResponseFromJSONTyped(json, false);
}

export function SearchKeyword200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): SearchKeyword200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'page': json['page'] == null ? undefined : json['page'],
        'results': json['results'] == null ? undefined : ((json['results'] as Array<any>).map(SearchKeyword200ResponseResultsInnerFromJSON)),
        'total_pages': json['total_pages'] == null ? undefined : json['total_pages'],
        'total_results': json['total_results'] == null ? undefined : json['total_results'],
    };
}

export function SearchKeyword200ResponseToJSON(value?: SearchKeyword200Response | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'page': value['page'],
        'results': value['results'] == null ? undefined : ((value['results'] as Array<any>).map(SearchKeyword200ResponseResultsInnerToJSON)),
        'total_pages': value['total_pages'],
        'total_results': value['total_results'],
    };
}

