/* tslint:disable */
/* eslint-disable */
/**
 * TMDB API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SearchCompany200ResponseResultsInner
 */
export interface SearchCompany200ResponseResultsInner {
    /**
     * 
     * @type {number}
     * @memberof SearchCompany200ResponseResultsInner
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof SearchCompany200ResponseResultsInner
     */
    logo_path?: string;
    /**
     * 
     * @type {string}
     * @memberof SearchCompany200ResponseResultsInner
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof SearchCompany200ResponseResultsInner
     */
    origin_country?: string;
}

/**
 * Check if a given object implements the SearchCompany200ResponseResultsInner interface.
 */
export function instanceOfSearchCompany200ResponseResultsInner(value: object): value is SearchCompany200ResponseResultsInner {
    return true;
}

export function SearchCompany200ResponseResultsInnerFromJSON(json: any): SearchCompany200ResponseResultsInner {
    return SearchCompany200ResponseResultsInnerFromJSONTyped(json, false);
}

export function SearchCompany200ResponseResultsInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): SearchCompany200ResponseResultsInner {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'logo_path': json['logo_path'] == null ? undefined : json['logo_path'],
        'name': json['name'] == null ? undefined : json['name'],
        'origin_country': json['origin_country'] == null ? undefined : json['origin_country'],
    };
}

export function SearchCompany200ResponseResultsInnerToJSON(value?: SearchCompany200ResponseResultsInner | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'id': value['id'],
        'logo_path': value['logo_path'],
        'name': value['name'],
        'origin_country': value['origin_country'],
    };
}

