/* tslint:disable */
/* eslint-disable */
/**
 * TMDB API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { SearchPerson200ResponseResultsInnerKnownForInner } from './SearchPerson200ResponseResultsInnerKnownForInner';
import {
    SearchPerson200ResponseResultsInnerKnownForInnerFromJSON,
    SearchPerson200ResponseResultsInnerKnownForInnerFromJSONTyped,
    SearchPerson200ResponseResultsInnerKnownForInnerToJSON,
} from './SearchPerson200ResponseResultsInnerKnownForInner';

/**
 * 
 * @export
 * @interface SearchPerson200ResponseResultsInner
 */
export interface SearchPerson200ResponseResultsInner {
    /**
     * 
     * @type {boolean}
     * @memberof SearchPerson200ResponseResultsInner
     */
    adult?: boolean;
    /**
     * 
     * @type {number}
     * @memberof SearchPerson200ResponseResultsInner
     */
    gender?: number;
    /**
     * 
     * @type {number}
     * @memberof SearchPerson200ResponseResultsInner
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof SearchPerson200ResponseResultsInner
     */
    known_for_department?: string;
    /**
     * 
     * @type {string}
     * @memberof SearchPerson200ResponseResultsInner
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof SearchPerson200ResponseResultsInner
     */
    original_name?: string;
    /**
     * 
     * @type {number}
     * @memberof SearchPerson200ResponseResultsInner
     */
    popularity?: number;
    /**
     * 
     * @type {string}
     * @memberof SearchPerson200ResponseResultsInner
     */
    profile_path?: string;
    /**
     * 
     * @type {Array<SearchPerson200ResponseResultsInnerKnownForInner>}
     * @memberof SearchPerson200ResponseResultsInner
     */
    known_for?: Array<SearchPerson200ResponseResultsInnerKnownForInner>;
}

/**
 * Check if a given object implements the SearchPerson200ResponseResultsInner interface.
 */
export function instanceOfSearchPerson200ResponseResultsInner(value: object): value is SearchPerson200ResponseResultsInner {
    return true;
}

export function SearchPerson200ResponseResultsInnerFromJSON(json: any): SearchPerson200ResponseResultsInner {
    return SearchPerson200ResponseResultsInnerFromJSONTyped(json, false);
}

export function SearchPerson200ResponseResultsInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): SearchPerson200ResponseResultsInner {
    if (json == null) {
        return json;
    }
    return {
        
        'adult': json['adult'] == null ? undefined : json['adult'],
        'gender': json['gender'] == null ? undefined : json['gender'],
        'id': json['id'] == null ? undefined : json['id'],
        'known_for_department': json['known_for_department'] == null ? undefined : json['known_for_department'],
        'name': json['name'] == null ? undefined : json['name'],
        'original_name': json['original_name'] == null ? undefined : json['original_name'],
        'popularity': json['popularity'] == null ? undefined : json['popularity'],
        'profile_path': json['profile_path'] == null ? undefined : json['profile_path'],
        'known_for': json['known_for'] == null ? undefined : ((json['known_for'] as Array<any>).map(SearchPerson200ResponseResultsInnerKnownForInnerFromJSON)),
    };
}

export function SearchPerson200ResponseResultsInnerToJSON(value?: SearchPerson200ResponseResultsInner | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'adult': value['adult'],
        'gender': value['gender'],
        'id': value['id'],
        'known_for_department': value['known_for_department'],
        'name': value['name'],
        'original_name': value['original_name'],
        'popularity': value['popularity'],
        'profile_path': value['profile_path'],
        'known_for': value['known_for'] == null ? undefined : ((value['known_for'] as Array<any>).map(SearchPerson200ResponseResultsInnerKnownForInnerToJSON)),
    };
}

