/* tslint:disable */
/* eslint-disable */
/**
 * TMDB API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface TvEpisodeGroupDetails200ResponseGroupsInnerEpisodesInner
 */
export interface TvEpisodeGroupDetails200ResponseGroupsInnerEpisodesInner {
    /**
     * 
     * @type {string}
     * @memberof TvEpisodeGroupDetails200ResponseGroupsInnerEpisodesInner
     */
    air_date?: string;
    /**
     * 
     * @type {number}
     * @memberof TvEpisodeGroupDetails200ResponseGroupsInnerEpisodesInner
     */
    episode_number?: number;
    /**
     * 
     * @type {number}
     * @memberof TvEpisodeGroupDetails200ResponseGroupsInnerEpisodesInner
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof TvEpisodeGroupDetails200ResponseGroupsInnerEpisodesInner
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof TvEpisodeGroupDetails200ResponseGroupsInnerEpisodesInner
     */
    overview?: string;
    /**
     * 
     * @type {string}
     * @memberof TvEpisodeGroupDetails200ResponseGroupsInnerEpisodesInner
     */
    production_code?: string;
    /**
     * 
     * @type {any}
     * @memberof TvEpisodeGroupDetails200ResponseGroupsInnerEpisodesInner
     */
    runtime?: any;
    /**
     * 
     * @type {number}
     * @memberof TvEpisodeGroupDetails200ResponseGroupsInnerEpisodesInner
     */
    season_number?: number;
    /**
     * 
     * @type {number}
     * @memberof TvEpisodeGroupDetails200ResponseGroupsInnerEpisodesInner
     */
    show_id?: number;
    /**
     * 
     * @type {string}
     * @memberof TvEpisodeGroupDetails200ResponseGroupsInnerEpisodesInner
     */
    still_path?: string;
    /**
     * 
     * @type {number}
     * @memberof TvEpisodeGroupDetails200ResponseGroupsInnerEpisodesInner
     */
    vote_average?: number;
    /**
     * 
     * @type {number}
     * @memberof TvEpisodeGroupDetails200ResponseGroupsInnerEpisodesInner
     */
    vote_count?: number;
    /**
     * 
     * @type {number}
     * @memberof TvEpisodeGroupDetails200ResponseGroupsInnerEpisodesInner
     */
    order?: number;
}

/**
 * Check if a given object implements the TvEpisodeGroupDetails200ResponseGroupsInnerEpisodesInner interface.
 */
export function instanceOfTvEpisodeGroupDetails200ResponseGroupsInnerEpisodesInner(value: object): value is TvEpisodeGroupDetails200ResponseGroupsInnerEpisodesInner {
    return true;
}

export function TvEpisodeGroupDetails200ResponseGroupsInnerEpisodesInnerFromJSON(json: any): TvEpisodeGroupDetails200ResponseGroupsInnerEpisodesInner {
    return TvEpisodeGroupDetails200ResponseGroupsInnerEpisodesInnerFromJSONTyped(json, false);
}

export function TvEpisodeGroupDetails200ResponseGroupsInnerEpisodesInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): TvEpisodeGroupDetails200ResponseGroupsInnerEpisodesInner {
    if (json == null) {
        return json;
    }
    return {
        
        'air_date': json['air_date'] == null ? undefined : json['air_date'],
        'episode_number': json['episode_number'] == null ? undefined : json['episode_number'],
        'id': json['id'] == null ? undefined : json['id'],
        'name': json['name'] == null ? undefined : json['name'],
        'overview': json['overview'] == null ? undefined : json['overview'],
        'production_code': json['production_code'] == null ? undefined : json['production_code'],
        'runtime': json['runtime'] == null ? undefined : json['runtime'],
        'season_number': json['season_number'] == null ? undefined : json['season_number'],
        'show_id': json['show_id'] == null ? undefined : json['show_id'],
        'still_path': json['still_path'] == null ? undefined : json['still_path'],
        'vote_average': json['vote_average'] == null ? undefined : json['vote_average'],
        'vote_count': json['vote_count'] == null ? undefined : json['vote_count'],
        'order': json['order'] == null ? undefined : json['order'],
    };
}

export function TvEpisodeGroupDetails200ResponseGroupsInnerEpisodesInnerToJSON(value?: TvEpisodeGroupDetails200ResponseGroupsInnerEpisodesInner | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'air_date': value['air_date'],
        'episode_number': value['episode_number'],
        'id': value['id'],
        'name': value['name'],
        'overview': value['overview'],
        'production_code': value['production_code'],
        'runtime': value['runtime'],
        'season_number': value['season_number'],
        'show_id': value['show_id'],
        'still_path': value['still_path'],
        'vote_average': value['vote_average'],
        'vote_count': value['vote_count'],
        'order': value['order'],
    };
}

