/* tslint:disable */
/* eslint-disable */
/**
 * TMDB API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { MovieAccountStates200ResponseRated } from './MovieAccountStates200ResponseRated';
import {
    MovieAccountStates200ResponseRatedFromJSON,
    MovieAccountStates200ResponseRatedFromJSONTyped,
    MovieAccountStates200ResponseRatedToJSON,
} from './MovieAccountStates200ResponseRated';

/**
 * 
 * @export
 * @interface TvSeasonAccountStates200ResponseResultsInner
 */
export interface TvSeasonAccountStates200ResponseResultsInner {
    /**
     * 
     * @type {number}
     * @memberof TvSeasonAccountStates200ResponseResultsInner
     */
    id?: number;
    /**
     * 
     * @type {number}
     * @memberof TvSeasonAccountStates200ResponseResultsInner
     */
    episode_number?: number;
    /**
     * 
     * @type {MovieAccountStates200ResponseRated}
     * @memberof TvSeasonAccountStates200ResponseResultsInner
     */
    rated?: MovieAccountStates200ResponseRated;
}

/**
 * Check if a given object implements the TvSeasonAccountStates200ResponseResultsInner interface.
 */
export function instanceOfTvSeasonAccountStates200ResponseResultsInner(value: object): value is TvSeasonAccountStates200ResponseResultsInner {
    return true;
}

export function TvSeasonAccountStates200ResponseResultsInnerFromJSON(json: any): TvSeasonAccountStates200ResponseResultsInner {
    return TvSeasonAccountStates200ResponseResultsInnerFromJSONTyped(json, false);
}

export function TvSeasonAccountStates200ResponseResultsInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): TvSeasonAccountStates200ResponseResultsInner {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'episode_number': json['episode_number'] == null ? undefined : json['episode_number'],
        'rated': json['rated'] == null ? undefined : MovieAccountStates200ResponseRatedFromJSON(json['rated']),
    };
}

export function TvSeasonAccountStates200ResponseResultsInnerToJSON(value?: TvSeasonAccountStates200ResponseResultsInner | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'id': value['id'],
        'episode_number': value['episode_number'],
        'rated': MovieAccountStates200ResponseRatedToJSON(value['rated']),
    };
}

