/* tslint:disable */
/* eslint-disable */
/**
 * TMDB API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface TvSeriesLatestId200ResponseLastEpisodeToAir
 */
export interface TvSeriesLatestId200ResponseLastEpisodeToAir {
    /**
     * 
     * @type {number}
     * @memberof TvSeriesLatestId200ResponseLastEpisodeToAir
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof TvSeriesLatestId200ResponseLastEpisodeToAir
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof TvSeriesLatestId200ResponseLastEpisodeToAir
     */
    overview?: string;
    /**
     * 
     * @type {number}
     * @memberof TvSeriesLatestId200ResponseLastEpisodeToAir
     */
    vote_average?: number;
    /**
     * 
     * @type {number}
     * @memberof TvSeriesLatestId200ResponseLastEpisodeToAir
     */
    vote_count?: number;
    /**
     * 
     * @type {string}
     * @memberof TvSeriesLatestId200ResponseLastEpisodeToAir
     */
    air_date?: string;
    /**
     * 
     * @type {number}
     * @memberof TvSeriesLatestId200ResponseLastEpisodeToAir
     */
    episode_number?: number;
    /**
     * 
     * @type {string}
     * @memberof TvSeriesLatestId200ResponseLastEpisodeToAir
     */
    production_code?: string;
    /**
     * 
     * @type {any}
     * @memberof TvSeriesLatestId200ResponseLastEpisodeToAir
     */
    runtime?: any;
    /**
     * 
     * @type {number}
     * @memberof TvSeriesLatestId200ResponseLastEpisodeToAir
     */
    season_number?: number;
    /**
     * 
     * @type {number}
     * @memberof TvSeriesLatestId200ResponseLastEpisodeToAir
     */
    show_id?: number;
    /**
     * 
     * @type {any}
     * @memberof TvSeriesLatestId200ResponseLastEpisodeToAir
     */
    still_path?: any;
}

/**
 * Check if a given object implements the TvSeriesLatestId200ResponseLastEpisodeToAir interface.
 */
export function instanceOfTvSeriesLatestId200ResponseLastEpisodeToAir(value: object): value is TvSeriesLatestId200ResponseLastEpisodeToAir {
    return true;
}

export function TvSeriesLatestId200ResponseLastEpisodeToAirFromJSON(json: any): TvSeriesLatestId200ResponseLastEpisodeToAir {
    return TvSeriesLatestId200ResponseLastEpisodeToAirFromJSONTyped(json, false);
}

export function TvSeriesLatestId200ResponseLastEpisodeToAirFromJSONTyped(json: any, ignoreDiscriminator: boolean): TvSeriesLatestId200ResponseLastEpisodeToAir {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'name': json['name'] == null ? undefined : json['name'],
        'overview': json['overview'] == null ? undefined : json['overview'],
        'vote_average': json['vote_average'] == null ? undefined : json['vote_average'],
        'vote_count': json['vote_count'] == null ? undefined : json['vote_count'],
        'air_date': json['air_date'] == null ? undefined : json['air_date'],
        'episode_number': json['episode_number'] == null ? undefined : json['episode_number'],
        'production_code': json['production_code'] == null ? undefined : json['production_code'],
        'runtime': json['runtime'] == null ? undefined : json['runtime'],
        'season_number': json['season_number'] == null ? undefined : json['season_number'],
        'show_id': json['show_id'] == null ? undefined : json['show_id'],
        'still_path': json['still_path'] == null ? undefined : json['still_path'],
    };
}

export function TvSeriesLatestId200ResponseLastEpisodeToAirToJSON(value?: TvSeriesLatestId200ResponseLastEpisodeToAir | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'id': value['id'],
        'name': value['name'],
        'overview': value['overview'],
        'vote_average': value['vote_average'],
        'vote_count': value['vote_count'],
        'air_date': value['air_date'],
        'episode_number': value['episode_number'],
        'production_code': value['production_code'],
        'runtime': value['runtime'],
        'season_number': value['season_number'],
        'show_id': value['show_id'],
        'still_path': value['still_path'],
    };
}

