/* tslint:disable */
/* eslint-disable */
/**
 * TMDB API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface TvSeriesContentRatings200ResponseResultsInner
 */
export interface TvSeriesContentRatings200ResponseResultsInner {
    /**
     * 
     * @type {Array<string>}
     * @memberof TvSeriesContentRatings200ResponseResultsInner
     */
    descriptors?: Array<string>;
    /**
     * 
     * @type {string}
     * @memberof TvSeriesContentRatings200ResponseResultsInner
     */
    iso_3166_1?: string;
    /**
     * 
     * @type {string}
     * @memberof TvSeriesContentRatings200ResponseResultsInner
     */
    rating?: string;
}

/**
 * Check if a given object implements the TvSeriesContentRatings200ResponseResultsInner interface.
 */
export function instanceOfTvSeriesContentRatings200ResponseResultsInner(value: object): value is TvSeriesContentRatings200ResponseResultsInner {
    return true;
}

export function TvSeriesContentRatings200ResponseResultsInnerFromJSON(json: any): TvSeriesContentRatings200ResponseResultsInner {
    return TvSeriesContentRatings200ResponseResultsInnerFromJSONTyped(json, false);
}

export function TvSeriesContentRatings200ResponseResultsInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): TvSeriesContentRatings200ResponseResultsInner {
    if (json == null) {
        return json;
    }
    return {
        
        'descriptors': json['descriptors'] == null ? undefined : json['descriptors'],
        'iso_3166_1': json['iso_3166_1'] == null ? undefined : json['iso_3166_1'],
        'rating': json['rating'] == null ? undefined : json['rating'],
    };
}

export function TvSeriesContentRatings200ResponseResultsInnerToJSON(value?: TvSeriesContentRatings200ResponseResultsInner | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'descriptors': value['descriptors'],
        'iso_3166_1': value['iso_3166_1'],
        'rating': value['rating'],
    };
}

