/* tslint:disable */
/* eslint-disable */
/**
 * TMDB API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { TvSeriesTopRatedList200ResponseResultsInner } from './TvSeriesTopRatedList200ResponseResultsInner';
import {
    TvSeriesTopRatedList200ResponseResultsInnerFromJSON,
    TvSeriesTopRatedList200ResponseResultsInnerFromJSONTyped,
    TvSeriesTopRatedList200ResponseResultsInnerToJSON,
} from './TvSeriesTopRatedList200ResponseResultsInner';

/**
 * 
 * @export
 * @interface TvSeriesTopRatedList200Response
 */
export interface TvSeriesTopRatedList200Response {
    /**
     * 
     * @type {number}
     * @memberof TvSeriesTopRatedList200Response
     */
    page?: number;
    /**
     * 
     * @type {Array<TvSeriesTopRatedList200ResponseResultsInner>}
     * @memberof TvSeriesTopRatedList200Response
     */
    results?: Array<TvSeriesTopRatedList200ResponseResultsInner>;
    /**
     * 
     * @type {number}
     * @memberof TvSeriesTopRatedList200Response
     */
    total_pages?: number;
    /**
     * 
     * @type {number}
     * @memberof TvSeriesTopRatedList200Response
     */
    total_results?: number;
}

/**
 * Check if a given object implements the TvSeriesTopRatedList200Response interface.
 */
export function instanceOfTvSeriesTopRatedList200Response(value: object): value is TvSeriesTopRatedList200Response {
    return true;
}

export function TvSeriesTopRatedList200ResponseFromJSON(json: any): TvSeriesTopRatedList200Response {
    return TvSeriesTopRatedList200ResponseFromJSONTyped(json, false);
}

export function TvSeriesTopRatedList200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): TvSeriesTopRatedList200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'page': json['page'] == null ? undefined : json['page'],
        'results': json['results'] == null ? undefined : ((json['results'] as Array<any>).map(TvSeriesTopRatedList200ResponseResultsInnerFromJSON)),
        'total_pages': json['total_pages'] == null ? undefined : json['total_pages'],
        'total_results': json['total_results'] == null ? undefined : json['total_results'],
    };
}

export function TvSeriesTopRatedList200ResponseToJSON(value?: TvSeriesTopRatedList200Response | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'page': value['page'],
        'results': value['results'] == null ? undefined : ((value['results'] as Array<any>).map(TvSeriesTopRatedList200ResponseResultsInnerToJSON)),
        'total_pages': value['total_pages'],
        'total_results': value['total_results'],
    };
}

