/* tslint:disable */
/* eslint-disable */
/**
 * TMDB API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface TvSeriesCredits200ResponseCrewInner
 */
export interface TvSeriesCredits200ResponseCrewInner {
    /**
     * 
     * @type {boolean}
     * @memberof TvSeriesCredits200ResponseCrewInner
     */
    adult?: boolean;
    /**
     * 
     * @type {number}
     * @memberof TvSeriesCredits200ResponseCrewInner
     */
    gender?: number;
    /**
     * 
     * @type {number}
     * @memberof TvSeriesCredits200ResponseCrewInner
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof TvSeriesCredits200ResponseCrewInner
     */
    known_for_department?: string;
    /**
     * 
     * @type {string}
     * @memberof TvSeriesCredits200ResponseCrewInner
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof TvSeriesCredits200ResponseCrewInner
     */
    original_name?: string;
    /**
     * 
     * @type {number}
     * @memberof TvSeriesCredits200ResponseCrewInner
     */
    popularity?: number;
    /**
     * 
     * @type {string}
     * @memberof TvSeriesCredits200ResponseCrewInner
     */
    profile_path?: string;
    /**
     * 
     * @type {string}
     * @memberof TvSeriesCredits200ResponseCrewInner
     */
    credit_id?: string;
    /**
     * 
     * @type {string}
     * @memberof TvSeriesCredits200ResponseCrewInner
     */
    department?: string;
    /**
     * 
     * @type {string}
     * @memberof TvSeriesCredits200ResponseCrewInner
     */
    job?: string;
}

/**
 * Check if a given object implements the TvSeriesCredits200ResponseCrewInner interface.
 */
export function instanceOfTvSeriesCredits200ResponseCrewInner(value: object): value is TvSeriesCredits200ResponseCrewInner {
    return true;
}

export function TvSeriesCredits200ResponseCrewInnerFromJSON(json: any): TvSeriesCredits200ResponseCrewInner {
    return TvSeriesCredits200ResponseCrewInnerFromJSONTyped(json, false);
}

export function TvSeriesCredits200ResponseCrewInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): TvSeriesCredits200ResponseCrewInner {
    if (json == null) {
        return json;
    }
    return {
        
        'adult': json['adult'] == null ? undefined : json['adult'],
        'gender': json['gender'] == null ? undefined : json['gender'],
        'id': json['id'] == null ? undefined : json['id'],
        'known_for_department': json['known_for_department'] == null ? undefined : json['known_for_department'],
        'name': json['name'] == null ? undefined : json['name'],
        'original_name': json['original_name'] == null ? undefined : json['original_name'],
        'popularity': json['popularity'] == null ? undefined : json['popularity'],
        'profile_path': json['profile_path'] == null ? undefined : json['profile_path'],
        'credit_id': json['credit_id'] == null ? undefined : json['credit_id'],
        'department': json['department'] == null ? undefined : json['department'],
        'job': json['job'] == null ? undefined : json['job'],
    };
}

export function TvSeriesCredits200ResponseCrewInnerToJSON(value?: TvSeriesCredits200ResponseCrewInner | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'adult': value['adult'],
        'gender': value['gender'],
        'id': value['id'],
        'known_for_department': value['known_for_department'],
        'name': value['name'],
        'original_name': value['original_name'],
        'popularity': value['popularity'],
        'profile_path': value['profile_path'],
        'credit_id': value['credit_id'],
        'department': value['department'],
        'job': value['job'],
    };
}

