/* tslint:disable */
/* eslint-disable */
/**
 * TMDB API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { TvSeasonDetails200ResponseEpisodesInner } from './TvSeasonDetails200ResponseEpisodesInner';
import {
    TvSeasonDetails200ResponseEpisodesInnerFromJSON,
    TvSeasonDetails200ResponseEpisodesInnerFromJSONTyped,
    TvSeasonDetails200ResponseEpisodesInnerToJSON,
} from './TvSeasonDetails200ResponseEpisodesInner';

/**
 * 
 * @export
 * @interface TvSeasonDetails200Response
 */
export interface TvSeasonDetails200Response {
    /**
     * 
     * @type {string}
     * @memberof TvSeasonDetails200Response
     */
    _id?: string;
    /**
     * 
     * @type {string}
     * @memberof TvSeasonDetails200Response
     */
    air_date?: string;
    /**
     * 
     * @type {Array<TvSeasonDetails200ResponseEpisodesInner>}
     * @memberof TvSeasonDetails200Response
     */
    episodes?: Array<TvSeasonDetails200ResponseEpisodesInner>;
    /**
     * 
     * @type {string}
     * @memberof TvSeasonDetails200Response
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof TvSeasonDetails200Response
     */
    overview?: string;
    /**
     * 
     * @type {number}
     * @memberof TvSeasonDetails200Response
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof TvSeasonDetails200Response
     */
    poster_path?: string;
    /**
     * 
     * @type {number}
     * @memberof TvSeasonDetails200Response
     */
    season_number?: number;
    /**
     * 
     * @type {number}
     * @memberof TvSeasonDetails200Response
     */
    vote_average?: number;
}

/**
 * Check if a given object implements the TvSeasonDetails200Response interface.
 */
export function instanceOfTvSeasonDetails200Response(value: object): value is TvSeasonDetails200Response {
    return true;
}

export function TvSeasonDetails200ResponseFromJSON(json: any): TvSeasonDetails200Response {
    return TvSeasonDetails200ResponseFromJSONTyped(json, false);
}

export function TvSeasonDetails200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): TvSeasonDetails200Response {
    if (json == null) {
        return json;
    }
    return {
        
        '_id': json['_id'] == null ? undefined : json['_id'],
        'air_date': json['air_date'] == null ? undefined : json['air_date'],
        'episodes': json['episodes'] == null ? undefined : ((json['episodes'] as Array<any>).map(TvSeasonDetails200ResponseEpisodesInnerFromJSON)),
        'name': json['name'] == null ? undefined : json['name'],
        'overview': json['overview'] == null ? undefined : json['overview'],
        'id': json['id'] == null ? undefined : json['id'],
        'poster_path': json['poster_path'] == null ? undefined : json['poster_path'],
        'season_number': json['season_number'] == null ? undefined : json['season_number'],
        'vote_average': json['vote_average'] == null ? undefined : json['vote_average'],
    };
}

export function TvSeasonDetails200ResponseToJSON(value?: TvSeasonDetails200Response | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        '_id': value['_id'],
        'air_date': value['air_date'],
        'episodes': value['episodes'] == null ? undefined : ((value['episodes'] as Array<any>).map(TvSeasonDetails200ResponseEpisodesInnerToJSON)),
        'name': value['name'],
        'overview': value['overview'],
        'id': value['id'],
        'poster_path': value['poster_path'],
        'season_number': value['season_number'],
        'vote_average': value['vote_average'],
    };
}

