/* tslint:disable */
/* eslint-disable */
/**
 * TMDB API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { TvSeasonAggregateCredits200ResponseCastInnerRolesInner } from './TvSeasonAggregateCredits200ResponseCastInnerRolesInner';
import {
    TvSeasonAggregateCredits200ResponseCastInnerRolesInnerFromJSON,
    TvSeasonAggregateCredits200ResponseCastInnerRolesInnerFromJSONTyped,
    TvSeasonAggregateCredits200ResponseCastInnerRolesInnerToJSON,
} from './TvSeasonAggregateCredits200ResponseCastInnerRolesInner';

/**
 * 
 * @export
 * @interface TvSeasonAggregateCredits200ResponseCastInner
 */
export interface TvSeasonAggregateCredits200ResponseCastInner {
    /**
     * 
     * @type {boolean}
     * @memberof TvSeasonAggregateCredits200ResponseCastInner
     */
    adult?: boolean;
    /**
     * 
     * @type {number}
     * @memberof TvSeasonAggregateCredits200ResponseCastInner
     */
    gender?: number;
    /**
     * 
     * @type {number}
     * @memberof TvSeasonAggregateCredits200ResponseCastInner
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof TvSeasonAggregateCredits200ResponseCastInner
     */
    known_for_department?: string;
    /**
     * 
     * @type {string}
     * @memberof TvSeasonAggregateCredits200ResponseCastInner
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof TvSeasonAggregateCredits200ResponseCastInner
     */
    original_name?: string;
    /**
     * 
     * @type {number}
     * @memberof TvSeasonAggregateCredits200ResponseCastInner
     */
    popularity?: number;
    /**
     * 
     * @type {string}
     * @memberof TvSeasonAggregateCredits200ResponseCastInner
     */
    profile_path?: string;
    /**
     * 
     * @type {Array<TvSeasonAggregateCredits200ResponseCastInnerRolesInner>}
     * @memberof TvSeasonAggregateCredits200ResponseCastInner
     */
    roles?: Array<TvSeasonAggregateCredits200ResponseCastInnerRolesInner>;
    /**
     * 
     * @type {number}
     * @memberof TvSeasonAggregateCredits200ResponseCastInner
     */
    total_episode_count?: number;
    /**
     * 
     * @type {number}
     * @memberof TvSeasonAggregateCredits200ResponseCastInner
     */
    order?: number;
}

/**
 * Check if a given object implements the TvSeasonAggregateCredits200ResponseCastInner interface.
 */
export function instanceOfTvSeasonAggregateCredits200ResponseCastInner(value: object): value is TvSeasonAggregateCredits200ResponseCastInner {
    return true;
}

export function TvSeasonAggregateCredits200ResponseCastInnerFromJSON(json: any): TvSeasonAggregateCredits200ResponseCastInner {
    return TvSeasonAggregateCredits200ResponseCastInnerFromJSONTyped(json, false);
}

export function TvSeasonAggregateCredits200ResponseCastInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): TvSeasonAggregateCredits200ResponseCastInner {
    if (json == null) {
        return json;
    }
    return {
        
        'adult': json['adult'] == null ? undefined : json['adult'],
        'gender': json['gender'] == null ? undefined : json['gender'],
        'id': json['id'] == null ? undefined : json['id'],
        'known_for_department': json['known_for_department'] == null ? undefined : json['known_for_department'],
        'name': json['name'] == null ? undefined : json['name'],
        'original_name': json['original_name'] == null ? undefined : json['original_name'],
        'popularity': json['popularity'] == null ? undefined : json['popularity'],
        'profile_path': json['profile_path'] == null ? undefined : json['profile_path'],
        'roles': json['roles'] == null ? undefined : ((json['roles'] as Array<any>).map(TvSeasonAggregateCredits200ResponseCastInnerRolesInnerFromJSON)),
        'total_episode_count': json['total_episode_count'] == null ? undefined : json['total_episode_count'],
        'order': json['order'] == null ? undefined : json['order'],
    };
}

export function TvSeasonAggregateCredits200ResponseCastInnerToJSON(value?: TvSeasonAggregateCredits200ResponseCastInner | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'adult': value['adult'],
        'gender': value['gender'],
        'id': value['id'],
        'known_for_department': value['known_for_department'],
        'name': value['name'],
        'original_name': value['original_name'],
        'popularity': value['popularity'],
        'profile_path': value['profile_path'],
        'roles': value['roles'] == null ? undefined : ((value['roles'] as Array<any>).map(TvSeasonAggregateCredits200ResponseCastInnerRolesInnerToJSON)),
        'total_episode_count': value['total_episode_count'],
        'order': value['order'],
    };
}

