/* tslint:disable */
/* eslint-disable */
/**
 * TMDB API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface TvSeriesChanges200ResponseChangesInnerItemsInnerOriginalValuePoster
 */
export interface TvSeriesChanges200ResponseChangesInnerItemsInnerOriginalValuePoster {
    /**
     * 
     * @type {string}
     * @memberof TvSeriesChanges200ResponseChangesInnerItemsInnerOriginalValuePoster
     */
    file_path?: string;
    /**
     * 
     * @type {string}
     * @memberof TvSeriesChanges200ResponseChangesInnerItemsInnerOriginalValuePoster
     */
    iso_639_1?: string;
}

/**
 * Check if a given object implements the TvSeriesChanges200ResponseChangesInnerItemsInnerOriginalValuePoster interface.
 */
export function instanceOfTvSeriesChanges200ResponseChangesInnerItemsInnerOriginalValuePoster(value: object): value is TvSeriesChanges200ResponseChangesInnerItemsInnerOriginalValuePoster {
    return true;
}

export function TvSeriesChanges200ResponseChangesInnerItemsInnerOriginalValuePosterFromJSON(json: any): TvSeriesChanges200ResponseChangesInnerItemsInnerOriginalValuePoster {
    return TvSeriesChanges200ResponseChangesInnerItemsInnerOriginalValuePosterFromJSONTyped(json, false);
}

export function TvSeriesChanges200ResponseChangesInnerItemsInnerOriginalValuePosterFromJSONTyped(json: any, ignoreDiscriminator: boolean): TvSeriesChanges200ResponseChangesInnerItemsInnerOriginalValuePoster {
    if (json == null) {
        return json;
    }
    return {
        
        'file_path': json['file_path'] == null ? undefined : json['file_path'],
        'iso_639_1': json['iso_639_1'] == null ? undefined : json['iso_639_1'],
    };
}

export function TvSeriesChanges200ResponseChangesInnerItemsInnerOriginalValuePosterToJSON(value?: TvSeriesChanges200ResponseChangesInnerItemsInnerOriginalValuePoster | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'file_path': value['file_path'],
        'iso_639_1': value['iso_639_1'],
    };
}

