/* tslint:disable */
/* eslint-disable */
/**
 * TMDB API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface TvSeriesAggregateCredits200ResponseCrewInnerJobsInner
 */
export interface TvSeriesAggregateCredits200ResponseCrewInnerJobsInner {
    /**
     * 
     * @type {string}
     * @memberof TvSeriesAggregateCredits200ResponseCrewInnerJobsInner
     */
    credit_id?: string;
    /**
     * 
     * @type {string}
     * @memberof TvSeriesAggregateCredits200ResponseCrewInnerJobsInner
     */
    job?: string;
    /**
     * 
     * @type {number}
     * @memberof TvSeriesAggregateCredits200ResponseCrewInnerJobsInner
     */
    episode_count?: number;
}

/**
 * Check if a given object implements the TvSeriesAggregateCredits200ResponseCrewInnerJobsInner interface.
 */
export function instanceOfTvSeriesAggregateCredits200ResponseCrewInnerJobsInner(value: object): value is TvSeriesAggregateCredits200ResponseCrewInnerJobsInner {
    return true;
}

export function TvSeriesAggregateCredits200ResponseCrewInnerJobsInnerFromJSON(json: any): TvSeriesAggregateCredits200ResponseCrewInnerJobsInner {
    return TvSeriesAggregateCredits200ResponseCrewInnerJobsInnerFromJSONTyped(json, false);
}

export function TvSeriesAggregateCredits200ResponseCrewInnerJobsInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): TvSeriesAggregateCredits200ResponseCrewInnerJobsInner {
    if (json == null) {
        return json;
    }
    return {
        
        'credit_id': json['credit_id'] == null ? undefined : json['credit_id'],
        'job': json['job'] == null ? undefined : json['job'],
        'episode_count': json['episode_count'] == null ? undefined : json['episode_count'],
    };
}

export function TvSeriesAggregateCredits200ResponseCrewInnerJobsInnerToJSON(value?: TvSeriesAggregateCredits200ResponseCrewInnerJobsInner | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'credit_id': value['credit_id'],
        'job': value['job'],
        'episode_count': value['episode_count'],
    };
}

