/* tslint:disable */
/* eslint-disable */
/**
 * TMDB API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface TvSeriesSimilar200ResponseResultsInner
 */
export interface TvSeriesSimilar200ResponseResultsInner {
    /**
     * 
     * @type {boolean}
     * @memberof TvSeriesSimilar200ResponseResultsInner
     */
    adult?: boolean;
    /**
     * 
     * @type {string}
     * @memberof TvSeriesSimilar200ResponseResultsInner
     */
    backdrop_path?: string;
    /**
     * 
     * @type {Array<number>}
     * @memberof TvSeriesSimilar200ResponseResultsInner
     */
    genre_ids?: Array<number>;
    /**
     * 
     * @type {number}
     * @memberof TvSeriesSimilar200ResponseResultsInner
     */
    id?: number;
    /**
     * 
     * @type {Array<string>}
     * @memberof TvSeriesSimilar200ResponseResultsInner
     */
    origin_country?: Array<string>;
    /**
     * 
     * @type {string}
     * @memberof TvSeriesSimilar200ResponseResultsInner
     */
    original_language?: string;
    /**
     * 
     * @type {string}
     * @memberof TvSeriesSimilar200ResponseResultsInner
     */
    original_name?: string;
    /**
     * 
     * @type {string}
     * @memberof TvSeriesSimilar200ResponseResultsInner
     */
    overview?: string;
    /**
     * 
     * @type {number}
     * @memberof TvSeriesSimilar200ResponseResultsInner
     */
    popularity?: number;
    /**
     * 
     * @type {string}
     * @memberof TvSeriesSimilar200ResponseResultsInner
     */
    poster_path?: string;
    /**
     * 
     * @type {string}
     * @memberof TvSeriesSimilar200ResponseResultsInner
     */
    first_air_date?: string;
    /**
     * 
     * @type {string}
     * @memberof TvSeriesSimilar200ResponseResultsInner
     */
    name?: string;
    /**
     * 
     * @type {number}
     * @memberof TvSeriesSimilar200ResponseResultsInner
     */
    vote_average?: number;
    /**
     * 
     * @type {number}
     * @memberof TvSeriesSimilar200ResponseResultsInner
     */
    vote_count?: number;
}

/**
 * Check if a given object implements the TvSeriesSimilar200ResponseResultsInner interface.
 */
export function instanceOfTvSeriesSimilar200ResponseResultsInner(value: object): value is TvSeriesSimilar200ResponseResultsInner {
    return true;
}

export function TvSeriesSimilar200ResponseResultsInnerFromJSON(json: any): TvSeriesSimilar200ResponseResultsInner {
    return TvSeriesSimilar200ResponseResultsInnerFromJSONTyped(json, false);
}

export function TvSeriesSimilar200ResponseResultsInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): TvSeriesSimilar200ResponseResultsInner {
    if (json == null) {
        return json;
    }
    return {
        
        'adult': json['adult'] == null ? undefined : json['adult'],
        'backdrop_path': json['backdrop_path'] == null ? undefined : json['backdrop_path'],
        'genre_ids': json['genre_ids'] == null ? undefined : json['genre_ids'],
        'id': json['id'] == null ? undefined : json['id'],
        'origin_country': json['origin_country'] == null ? undefined : json['origin_country'],
        'original_language': json['original_language'] == null ? undefined : json['original_language'],
        'original_name': json['original_name'] == null ? undefined : json['original_name'],
        'overview': json['overview'] == null ? undefined : json['overview'],
        'popularity': json['popularity'] == null ? undefined : json['popularity'],
        'poster_path': json['poster_path'] == null ? undefined : json['poster_path'],
        'first_air_date': json['first_air_date'] == null ? undefined : json['first_air_date'],
        'name': json['name'] == null ? undefined : json['name'],
        'vote_average': json['vote_average'] == null ? undefined : json['vote_average'],
        'vote_count': json['vote_count'] == null ? undefined : json['vote_count'],
    };
}

export function TvSeriesSimilar200ResponseResultsInnerToJSON(value?: TvSeriesSimilar200ResponseResultsInner | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'adult': value['adult'],
        'backdrop_path': value['backdrop_path'],
        'genre_ids': value['genre_ids'],
        'id': value['id'],
        'origin_country': value['origin_country'],
        'original_language': value['original_language'],
        'original_name': value['original_name'],
        'overview': value['overview'],
        'popularity': value['popularity'],
        'poster_path': value['poster_path'],
        'first_air_date': value['first_air_date'],
        'name': value['name'],
        'vote_average': value['vote_average'],
        'vote_count': value['vote_count'],
    };
}

