/* tslint:disable */
/* eslint-disable */
/**
 * TMDB API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { TvSeasonDetails200ResponseEpisodesInnerGuestStarsInner } from './TvSeasonDetails200ResponseEpisodesInnerGuestStarsInner';
import {
    TvSeasonDetails200ResponseEpisodesInnerGuestStarsInnerFromJSON,
    TvSeasonDetails200ResponseEpisodesInnerGuestStarsInnerFromJSONTyped,
    TvSeasonDetails200ResponseEpisodesInnerGuestStarsInnerToJSON,
} from './TvSeasonDetails200ResponseEpisodesInnerGuestStarsInner';
import type { TvSeasonDetails200ResponseEpisodesInnerCrewInner } from './TvSeasonDetails200ResponseEpisodesInnerCrewInner';
import {
    TvSeasonDetails200ResponseEpisodesInnerCrewInnerFromJSON,
    TvSeasonDetails200ResponseEpisodesInnerCrewInnerFromJSONTyped,
    TvSeasonDetails200ResponseEpisodesInnerCrewInnerToJSON,
} from './TvSeasonDetails200ResponseEpisodesInnerCrewInner';

/**
 * 
 * @export
 * @interface TvSeasonDetails200ResponseEpisodesInner
 */
export interface TvSeasonDetails200ResponseEpisodesInner {
    /**
     * 
     * @type {string}
     * @memberof TvSeasonDetails200ResponseEpisodesInner
     */
    air_date?: string;
    /**
     * 
     * @type {number}
     * @memberof TvSeasonDetails200ResponseEpisodesInner
     */
    episode_number?: number;
    /**
     * 
     * @type {number}
     * @memberof TvSeasonDetails200ResponseEpisodesInner
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof TvSeasonDetails200ResponseEpisodesInner
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof TvSeasonDetails200ResponseEpisodesInner
     */
    overview?: string;
    /**
     * 
     * @type {string}
     * @memberof TvSeasonDetails200ResponseEpisodesInner
     */
    production_code?: string;
    /**
     * 
     * @type {number}
     * @memberof TvSeasonDetails200ResponseEpisodesInner
     */
    runtime?: number;
    /**
     * 
     * @type {number}
     * @memberof TvSeasonDetails200ResponseEpisodesInner
     */
    season_number?: number;
    /**
     * 
     * @type {number}
     * @memberof TvSeasonDetails200ResponseEpisodesInner
     */
    show_id?: number;
    /**
     * 
     * @type {string}
     * @memberof TvSeasonDetails200ResponseEpisodesInner
     */
    still_path?: string;
    /**
     * 
     * @type {number}
     * @memberof TvSeasonDetails200ResponseEpisodesInner
     */
    vote_average?: number;
    /**
     * 
     * @type {number}
     * @memberof TvSeasonDetails200ResponseEpisodesInner
     */
    vote_count?: number;
    /**
     * 
     * @type {Array<TvSeasonDetails200ResponseEpisodesInnerCrewInner>}
     * @memberof TvSeasonDetails200ResponseEpisodesInner
     */
    crew?: Array<TvSeasonDetails200ResponseEpisodesInnerCrewInner>;
    /**
     * 
     * @type {Array<TvSeasonDetails200ResponseEpisodesInnerGuestStarsInner>}
     * @memberof TvSeasonDetails200ResponseEpisodesInner
     */
    guest_stars?: Array<TvSeasonDetails200ResponseEpisodesInnerGuestStarsInner>;
}

/**
 * Check if a given object implements the TvSeasonDetails200ResponseEpisodesInner interface.
 */
export function instanceOfTvSeasonDetails200ResponseEpisodesInner(value: object): value is TvSeasonDetails200ResponseEpisodesInner {
    return true;
}

export function TvSeasonDetails200ResponseEpisodesInnerFromJSON(json: any): TvSeasonDetails200ResponseEpisodesInner {
    return TvSeasonDetails200ResponseEpisodesInnerFromJSONTyped(json, false);
}

export function TvSeasonDetails200ResponseEpisodesInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): TvSeasonDetails200ResponseEpisodesInner {
    if (json == null) {
        return json;
    }
    return {
        
        'air_date': json['air_date'] == null ? undefined : json['air_date'],
        'episode_number': json['episode_number'] == null ? undefined : json['episode_number'],
        'id': json['id'] == null ? undefined : json['id'],
        'name': json['name'] == null ? undefined : json['name'],
        'overview': json['overview'] == null ? undefined : json['overview'],
        'production_code': json['production_code'] == null ? undefined : json['production_code'],
        'runtime': json['runtime'] == null ? undefined : json['runtime'],
        'season_number': json['season_number'] == null ? undefined : json['season_number'],
        'show_id': json['show_id'] == null ? undefined : json['show_id'],
        'still_path': json['still_path'] == null ? undefined : json['still_path'],
        'vote_average': json['vote_average'] == null ? undefined : json['vote_average'],
        'vote_count': json['vote_count'] == null ? undefined : json['vote_count'],
        'crew': json['crew'] == null ? undefined : ((json['crew'] as Array<any>).map(TvSeasonDetails200ResponseEpisodesInnerCrewInnerFromJSON)),
        'guest_stars': json['guest_stars'] == null ? undefined : ((json['guest_stars'] as Array<any>).map(TvSeasonDetails200ResponseEpisodesInnerGuestStarsInnerFromJSON)),
    };
}

export function TvSeasonDetails200ResponseEpisodesInnerToJSON(value?: TvSeasonDetails200ResponseEpisodesInner | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'air_date': value['air_date'],
        'episode_number': value['episode_number'],
        'id': value['id'],
        'name': value['name'],
        'overview': value['overview'],
        'production_code': value['production_code'],
        'runtime': value['runtime'],
        'season_number': value['season_number'],
        'show_id': value['show_id'],
        'still_path': value['still_path'],
        'vote_average': value['vote_average'],
        'vote_count': value['vote_count'],
        'crew': value['crew'] == null ? undefined : ((value['crew'] as Array<any>).map(TvSeasonDetails200ResponseEpisodesInnerCrewInnerToJSON)),
        'guest_stars': value['guest_stars'] == null ? undefined : ((value['guest_stars'] as Array<any>).map(TvSeasonDetails200ResponseEpisodesInnerGuestStarsInnerToJSON)),
    };
}

