/* tslint:disable */
/* eslint-disable */
/**
 * TMDB API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface TvSeriesScreenedTheatrically200ResponseResultsInner
 */
export interface TvSeriesScreenedTheatrically200ResponseResultsInner {
    /**
     * 
     * @type {number}
     * @memberof TvSeriesScreenedTheatrically200ResponseResultsInner
     */
    id?: number;
    /**
     * 
     * @type {number}
     * @memberof TvSeriesScreenedTheatrically200ResponseResultsInner
     */
    episode_number?: number;
    /**
     * 
     * @type {number}
     * @memberof TvSeriesScreenedTheatrically200ResponseResultsInner
     */
    season_number?: number;
}

/**
 * Check if a given object implements the TvSeriesScreenedTheatrically200ResponseResultsInner interface.
 */
export function instanceOfTvSeriesScreenedTheatrically200ResponseResultsInner(value: object): value is TvSeriesScreenedTheatrically200ResponseResultsInner {
    return true;
}

export function TvSeriesScreenedTheatrically200ResponseResultsInnerFromJSON(json: any): TvSeriesScreenedTheatrically200ResponseResultsInner {
    return TvSeriesScreenedTheatrically200ResponseResultsInnerFromJSONTyped(json, false);
}

export function TvSeriesScreenedTheatrically200ResponseResultsInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): TvSeriesScreenedTheatrically200ResponseResultsInner {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'episode_number': json['episode_number'] == null ? undefined : json['episode_number'],
        'season_number': json['season_number'] == null ? undefined : json['season_number'],
    };
}

export function TvSeriesScreenedTheatrically200ResponseResultsInnerToJSON(value?: TvSeriesScreenedTheatrically200ResponseResultsInner | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'id': value['id'],
        'episode_number': value['episode_number'],
        'season_number': value['season_number'],
    };
}

