/* tslint:disable */
/* eslint-disable */
/**
 * TMDB API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { TvSeriesLatestId200ResponseSeasonsInner } from './TvSeriesLatestId200ResponseSeasonsInner';
import {
    TvSeriesLatestId200ResponseSeasonsInnerFromJSON,
    TvSeriesLatestId200ResponseSeasonsInnerFromJSONTyped,
    TvSeriesLatestId200ResponseSeasonsInnerToJSON,
} from './TvSeriesLatestId200ResponseSeasonsInner';
import type { TvSeriesLatestId200ResponseLastEpisodeToAir } from './TvSeriesLatestId200ResponseLastEpisodeToAir';
import {
    TvSeriesLatestId200ResponseLastEpisodeToAirFromJSON,
    TvSeriesLatestId200ResponseLastEpisodeToAirFromJSONTyped,
    TvSeriesLatestId200ResponseLastEpisodeToAirToJSON,
} from './TvSeriesLatestId200ResponseLastEpisodeToAir';

/**
 * 
 * @export
 * @interface TvSeriesLatestId200Response
 */
export interface TvSeriesLatestId200Response {
    /**
     * 
     * @type {boolean}
     * @memberof TvSeriesLatestId200Response
     */
    adult?: boolean;
    /**
     * 
     * @type {any}
     * @memberof TvSeriesLatestId200Response
     */
    backdrop_path?: any;
    /**
     * 
     * @type {Array<string>}
     * @memberof TvSeriesLatestId200Response
     */
    created_by?: Array<string>;
    /**
     * 
     * @type {Array<string>}
     * @memberof TvSeriesLatestId200Response
     */
    episode_run_time?: Array<string>;
    /**
     * 
     * @type {string}
     * @memberof TvSeriesLatestId200Response
     */
    first_air_date?: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof TvSeriesLatestId200Response
     */
    genres?: Array<string>;
    /**
     * 
     * @type {string}
     * @memberof TvSeriesLatestId200Response
     */
    homepage?: string;
    /**
     * 
     * @type {number}
     * @memberof TvSeriesLatestId200Response
     */
    id?: number;
    /**
     * 
     * @type {boolean}
     * @memberof TvSeriesLatestId200Response
     */
    in_production?: boolean;
    /**
     * 
     * @type {Array<string>}
     * @memberof TvSeriesLatestId200Response
     */
    languages?: Array<string>;
    /**
     * 
     * @type {string}
     * @memberof TvSeriesLatestId200Response
     */
    last_air_date?: string;
    /**
     * 
     * @type {TvSeriesLatestId200ResponseLastEpisodeToAir}
     * @memberof TvSeriesLatestId200Response
     */
    last_episode_to_air?: TvSeriesLatestId200ResponseLastEpisodeToAir;
    /**
     * 
     * @type {string}
     * @memberof TvSeriesLatestId200Response
     */
    name?: string;
    /**
     * 
     * @type {any}
     * @memberof TvSeriesLatestId200Response
     */
    next_episode_to_air?: any;
    /**
     * 
     * @type {Array<string>}
     * @memberof TvSeriesLatestId200Response
     */
    networks?: Array<string>;
    /**
     * 
     * @type {number}
     * @memberof TvSeriesLatestId200Response
     */
    number_of_episodes?: number;
    /**
     * 
     * @type {number}
     * @memberof TvSeriesLatestId200Response
     */
    number_of_seasons?: number;
    /**
     * 
     * @type {Array<string>}
     * @memberof TvSeriesLatestId200Response
     */
    origin_country?: Array<string>;
    /**
     * 
     * @type {string}
     * @memberof TvSeriesLatestId200Response
     */
    original_language?: string;
    /**
     * 
     * @type {string}
     * @memberof TvSeriesLatestId200Response
     */
    original_name?: string;
    /**
     * 
     * @type {string}
     * @memberof TvSeriesLatestId200Response
     */
    overview?: string;
    /**
     * 
     * @type {number}
     * @memberof TvSeriesLatestId200Response
     */
    popularity?: number;
    /**
     * 
     * @type {any}
     * @memberof TvSeriesLatestId200Response
     */
    poster_path?: any;
    /**
     * 
     * @type {Array<string>}
     * @memberof TvSeriesLatestId200Response
     */
    production_companies?: Array<string>;
    /**
     * 
     * @type {Array<string>}
     * @memberof TvSeriesLatestId200Response
     */
    production_countries?: Array<string>;
    /**
     * 
     * @type {Array<TvSeriesLatestId200ResponseSeasonsInner>}
     * @memberof TvSeriesLatestId200Response
     */
    seasons?: Array<TvSeriesLatestId200ResponseSeasonsInner>;
    /**
     * 
     * @type {Array<string>}
     * @memberof TvSeriesLatestId200Response
     */
    spoken_languages?: Array<string>;
    /**
     * 
     * @type {string}
     * @memberof TvSeriesLatestId200Response
     */
    status?: string;
    /**
     * 
     * @type {string}
     * @memberof TvSeriesLatestId200Response
     */
    tagline?: string;
    /**
     * 
     * @type {string}
     * @memberof TvSeriesLatestId200Response
     */
    type?: string;
    /**
     * 
     * @type {number}
     * @memberof TvSeriesLatestId200Response
     */
    vote_average?: number;
    /**
     * 
     * @type {number}
     * @memberof TvSeriesLatestId200Response
     */
    vote_count?: number;
}

/**
 * Check if a given object implements the TvSeriesLatestId200Response interface.
 */
export function instanceOfTvSeriesLatestId200Response(value: object): value is TvSeriesLatestId200Response {
    return true;
}

export function TvSeriesLatestId200ResponseFromJSON(json: any): TvSeriesLatestId200Response {
    return TvSeriesLatestId200ResponseFromJSONTyped(json, false);
}

export function TvSeriesLatestId200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): TvSeriesLatestId200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'adult': json['adult'] == null ? undefined : json['adult'],
        'backdrop_path': json['backdrop_path'] == null ? undefined : json['backdrop_path'],
        'created_by': json['created_by'] == null ? undefined : json['created_by'],
        'episode_run_time': json['episode_run_time'] == null ? undefined : json['episode_run_time'],
        'first_air_date': json['first_air_date'] == null ? undefined : json['first_air_date'],
        'genres': json['genres'] == null ? undefined : json['genres'],
        'homepage': json['homepage'] == null ? undefined : json['homepage'],
        'id': json['id'] == null ? undefined : json['id'],
        'in_production': json['in_production'] == null ? undefined : json['in_production'],
        'languages': json['languages'] == null ? undefined : json['languages'],
        'last_air_date': json['last_air_date'] == null ? undefined : json['last_air_date'],
        'last_episode_to_air': json['last_episode_to_air'] == null ? undefined : TvSeriesLatestId200ResponseLastEpisodeToAirFromJSON(json['last_episode_to_air']),
        'name': json['name'] == null ? undefined : json['name'],
        'next_episode_to_air': json['next_episode_to_air'] == null ? undefined : json['next_episode_to_air'],
        'networks': json['networks'] == null ? undefined : json['networks'],
        'number_of_episodes': json['number_of_episodes'] == null ? undefined : json['number_of_episodes'],
        'number_of_seasons': json['number_of_seasons'] == null ? undefined : json['number_of_seasons'],
        'origin_country': json['origin_country'] == null ? undefined : json['origin_country'],
        'original_language': json['original_language'] == null ? undefined : json['original_language'],
        'original_name': json['original_name'] == null ? undefined : json['original_name'],
        'overview': json['overview'] == null ? undefined : json['overview'],
        'popularity': json['popularity'] == null ? undefined : json['popularity'],
        'poster_path': json['poster_path'] == null ? undefined : json['poster_path'],
        'production_companies': json['production_companies'] == null ? undefined : json['production_companies'],
        'production_countries': json['production_countries'] == null ? undefined : json['production_countries'],
        'seasons': json['seasons'] == null ? undefined : ((json['seasons'] as Array<any>).map(TvSeriesLatestId200ResponseSeasonsInnerFromJSON)),
        'spoken_languages': json['spoken_languages'] == null ? undefined : json['spoken_languages'],
        'status': json['status'] == null ? undefined : json['status'],
        'tagline': json['tagline'] == null ? undefined : json['tagline'],
        'type': json['type'] == null ? undefined : json['type'],
        'vote_average': json['vote_average'] == null ? undefined : json['vote_average'],
        'vote_count': json['vote_count'] == null ? undefined : json['vote_count'],
    };
}

export function TvSeriesLatestId200ResponseToJSON(value?: TvSeriesLatestId200Response | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'adult': value['adult'],
        'backdrop_path': value['backdrop_path'],
        'created_by': value['created_by'],
        'episode_run_time': value['episode_run_time'],
        'first_air_date': value['first_air_date'],
        'genres': value['genres'],
        'homepage': value['homepage'],
        'id': value['id'],
        'in_production': value['in_production'],
        'languages': value['languages'],
        'last_air_date': value['last_air_date'],
        'last_episode_to_air': TvSeriesLatestId200ResponseLastEpisodeToAirToJSON(value['last_episode_to_air']),
        'name': value['name'],
        'next_episode_to_air': value['next_episode_to_air'],
        'networks': value['networks'],
        'number_of_episodes': value['number_of_episodes'],
        'number_of_seasons': value['number_of_seasons'],
        'origin_country': value['origin_country'],
        'original_language': value['original_language'],
        'original_name': value['original_name'],
        'overview': value['overview'],
        'popularity': value['popularity'],
        'poster_path': value['poster_path'],
        'production_companies': value['production_companies'],
        'production_countries': value['production_countries'],
        'seasons': value['seasons'] == null ? undefined : ((value['seasons'] as Array<any>).map(TvSeriesLatestId200ResponseSeasonsInnerToJSON)),
        'spoken_languages': value['spoken_languages'],
        'status': value['status'],
        'tagline': value['tagline'],
        'type': value['type'],
        'vote_average': value['vote_average'],
        'vote_count': value['vote_count'],
    };
}

