/* tslint:disable */
/* eslint-disable */
/**
 * TMDB API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface TvSeriesVideos200ResponseResultsInner
 */
export interface TvSeriesVideos200ResponseResultsInner {
    /**
     * 
     * @type {string}
     * @memberof TvSeriesVideos200ResponseResultsInner
     */
    iso_639_1?: string;
    /**
     * 
     * @type {string}
     * @memberof TvSeriesVideos200ResponseResultsInner
     */
    iso_3166_1?: string;
    /**
     * 
     * @type {string}
     * @memberof TvSeriesVideos200ResponseResultsInner
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof TvSeriesVideos200ResponseResultsInner
     */
    key?: string;
    /**
     * 
     * @type {string}
     * @memberof TvSeriesVideos200ResponseResultsInner
     */
    site?: string;
    /**
     * 
     * @type {number}
     * @memberof TvSeriesVideos200ResponseResultsInner
     */
    size?: number;
    /**
     * 
     * @type {string}
     * @memberof TvSeriesVideos200ResponseResultsInner
     */
    type?: string;
    /**
     * 
     * @type {boolean}
     * @memberof TvSeriesVideos200ResponseResultsInner
     */
    official?: boolean;
    /**
     * 
     * @type {string}
     * @memberof TvSeriesVideos200ResponseResultsInner
     */
    published_at?: string;
    /**
     * 
     * @type {string}
     * @memberof TvSeriesVideos200ResponseResultsInner
     */
    id?: string;
}

/**
 * Check if a given object implements the TvSeriesVideos200ResponseResultsInner interface.
 */
export function instanceOfTvSeriesVideos200ResponseResultsInner(value: object): value is TvSeriesVideos200ResponseResultsInner {
    return true;
}

export function TvSeriesVideos200ResponseResultsInnerFromJSON(json: any): TvSeriesVideos200ResponseResultsInner {
    return TvSeriesVideos200ResponseResultsInnerFromJSONTyped(json, false);
}

export function TvSeriesVideos200ResponseResultsInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): TvSeriesVideos200ResponseResultsInner {
    if (json == null) {
        return json;
    }
    return {
        
        'iso_639_1': json['iso_639_1'] == null ? undefined : json['iso_639_1'],
        'iso_3166_1': json['iso_3166_1'] == null ? undefined : json['iso_3166_1'],
        'name': json['name'] == null ? undefined : json['name'],
        'key': json['key'] == null ? undefined : json['key'],
        'site': json['site'] == null ? undefined : json['site'],
        'size': json['size'] == null ? undefined : json['size'],
        'type': json['type'] == null ? undefined : json['type'],
        'official': json['official'] == null ? undefined : json['official'],
        'published_at': json['published_at'] == null ? undefined : json['published_at'],
        'id': json['id'] == null ? undefined : json['id'],
    };
}

export function TvSeriesVideos200ResponseResultsInnerToJSON(value?: TvSeriesVideos200ResponseResultsInner | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'iso_639_1': value['iso_639_1'],
        'iso_3166_1': value['iso_3166_1'],
        'name': value['name'],
        'key': value['key'],
        'site': value['site'],
        'size': value['size'],
        'type': value['type'],
        'official': value['official'],
        'published_at': value['published_at'],
        'id': value['id'],
    };
}

