/* tslint:disable */
/* eslint-disable */
/**
 * TMDB API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { TvSeriesTranslations200ResponseTranslationsInnerData } from './TvSeriesTranslations200ResponseTranslationsInnerData';
import {
    TvSeriesTranslations200ResponseTranslationsInnerDataFromJSON,
    TvSeriesTranslations200ResponseTranslationsInnerDataFromJSONTyped,
    TvSeriesTranslations200ResponseTranslationsInnerDataToJSON,
} from './TvSeriesTranslations200ResponseTranslationsInnerData';

/**
 * 
 * @export
 * @interface TvSeriesTranslations200ResponseTranslationsInner
 */
export interface TvSeriesTranslations200ResponseTranslationsInner {
    /**
     * 
     * @type {string}
     * @memberof TvSeriesTranslations200ResponseTranslationsInner
     */
    iso_3166_1?: string;
    /**
     * 
     * @type {string}
     * @memberof TvSeriesTranslations200ResponseTranslationsInner
     */
    iso_639_1?: string;
    /**
     * 
     * @type {string}
     * @memberof TvSeriesTranslations200ResponseTranslationsInner
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof TvSeriesTranslations200ResponseTranslationsInner
     */
    english_name?: string;
    /**
     * 
     * @type {TvSeriesTranslations200ResponseTranslationsInnerData}
     * @memberof TvSeriesTranslations200ResponseTranslationsInner
     */
    data?: TvSeriesTranslations200ResponseTranslationsInnerData;
}

/**
 * Check if a given object implements the TvSeriesTranslations200ResponseTranslationsInner interface.
 */
export function instanceOfTvSeriesTranslations200ResponseTranslationsInner(value: object): value is TvSeriesTranslations200ResponseTranslationsInner {
    return true;
}

export function TvSeriesTranslations200ResponseTranslationsInnerFromJSON(json: any): TvSeriesTranslations200ResponseTranslationsInner {
    return TvSeriesTranslations200ResponseTranslationsInnerFromJSONTyped(json, false);
}

export function TvSeriesTranslations200ResponseTranslationsInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): TvSeriesTranslations200ResponseTranslationsInner {
    if (json == null) {
        return json;
    }
    return {
        
        'iso_3166_1': json['iso_3166_1'] == null ? undefined : json['iso_3166_1'],
        'iso_639_1': json['iso_639_1'] == null ? undefined : json['iso_639_1'],
        'name': json['name'] == null ? undefined : json['name'],
        'english_name': json['english_name'] == null ? undefined : json['english_name'],
        'data': json['data'] == null ? undefined : TvSeriesTranslations200ResponseTranslationsInnerDataFromJSON(json['data']),
    };
}

export function TvSeriesTranslations200ResponseTranslationsInnerToJSON(value?: TvSeriesTranslations200ResponseTranslationsInner | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'iso_3166_1': value['iso_3166_1'],
        'iso_639_1': value['iso_639_1'],
        'name': value['name'],
        'english_name': value['english_name'],
        'data': TvSeriesTranslations200ResponseTranslationsInnerDataToJSON(value['data']),
    };
}

