/* tslint:disable */
/* eslint-disable */
/**
 * TMDB API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { TvSeriesReviews200ResponseResultsInnerAuthorDetails } from './TvSeriesReviews200ResponseResultsInnerAuthorDetails';
import {
    TvSeriesReviews200ResponseResultsInnerAuthorDetailsFromJSON,
    TvSeriesReviews200ResponseResultsInnerAuthorDetailsFromJSONTyped,
    TvSeriesReviews200ResponseResultsInnerAuthorDetailsToJSON,
} from './TvSeriesReviews200ResponseResultsInnerAuthorDetails';

/**
 * 
 * @export
 * @interface TvSeriesReviews200ResponseResultsInner
 */
export interface TvSeriesReviews200ResponseResultsInner {
    /**
     * 
     * @type {string}
     * @memberof TvSeriesReviews200ResponseResultsInner
     */
    author?: string;
    /**
     * 
     * @type {TvSeriesReviews200ResponseResultsInnerAuthorDetails}
     * @memberof TvSeriesReviews200ResponseResultsInner
     */
    author_details?: TvSeriesReviews200ResponseResultsInnerAuthorDetails;
    /**
     * 
     * @type {string}
     * @memberof TvSeriesReviews200ResponseResultsInner
     */
    content?: string;
    /**
     * 
     * @type {string}
     * @memberof TvSeriesReviews200ResponseResultsInner
     */
    created_at?: string;
    /**
     * 
     * @type {string}
     * @memberof TvSeriesReviews200ResponseResultsInner
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof TvSeriesReviews200ResponseResultsInner
     */
    updated_at?: string;
    /**
     * 
     * @type {string}
     * @memberof TvSeriesReviews200ResponseResultsInner
     */
    url?: string;
}

/**
 * Check if a given object implements the TvSeriesReviews200ResponseResultsInner interface.
 */
export function instanceOfTvSeriesReviews200ResponseResultsInner(value: object): value is TvSeriesReviews200ResponseResultsInner {
    return true;
}

export function TvSeriesReviews200ResponseResultsInnerFromJSON(json: any): TvSeriesReviews200ResponseResultsInner {
    return TvSeriesReviews200ResponseResultsInnerFromJSONTyped(json, false);
}

export function TvSeriesReviews200ResponseResultsInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): TvSeriesReviews200ResponseResultsInner {
    if (json == null) {
        return json;
    }
    return {
        
        'author': json['author'] == null ? undefined : json['author'],
        'author_details': json['author_details'] == null ? undefined : TvSeriesReviews200ResponseResultsInnerAuthorDetailsFromJSON(json['author_details']),
        'content': json['content'] == null ? undefined : json['content'],
        'created_at': json['created_at'] == null ? undefined : json['created_at'],
        'id': json['id'] == null ? undefined : json['id'],
        'updated_at': json['updated_at'] == null ? undefined : json['updated_at'],
        'url': json['url'] == null ? undefined : json['url'],
    };
}

export function TvSeriesReviews200ResponseResultsInnerToJSON(value?: TvSeriesReviews200ResponseResultsInner | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'author': value['author'],
        'author_details': TvSeriesReviews200ResponseResultsInnerAuthorDetailsToJSON(value['author_details']),
        'content': value['content'],
        'created_at': value['created_at'],
        'id': value['id'],
        'updated_at': value['updated_at'],
        'url': value['url'],
    };
}

