/* tslint:disable */
/* eslint-disable */
/**
 * TMDB API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface TvSeriesDetails200ResponseCreatedByInner
 */
export interface TvSeriesDetails200ResponseCreatedByInner {
    /**
     * 
     * @type {number}
     * @memberof TvSeriesDetails200ResponseCreatedByInner
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof TvSeriesDetails200ResponseCreatedByInner
     */
    credit_id?: string;
    /**
     * 
     * @type {string}
     * @memberof TvSeriesDetails200ResponseCreatedByInner
     */
    name?: string;
    /**
     * 
     * @type {number}
     * @memberof TvSeriesDetails200ResponseCreatedByInner
     */
    gender?: number;
    /**
     * 
     * @type {string}
     * @memberof TvSeriesDetails200ResponseCreatedByInner
     */
    profile_path?: string;
}

/**
 * Check if a given object implements the TvSeriesDetails200ResponseCreatedByInner interface.
 */
export function instanceOfTvSeriesDetails200ResponseCreatedByInner(value: object): value is TvSeriesDetails200ResponseCreatedByInner {
    return true;
}

export function TvSeriesDetails200ResponseCreatedByInnerFromJSON(json: any): TvSeriesDetails200ResponseCreatedByInner {
    return TvSeriesDetails200ResponseCreatedByInnerFromJSONTyped(json, false);
}

export function TvSeriesDetails200ResponseCreatedByInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): TvSeriesDetails200ResponseCreatedByInner {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'credit_id': json['credit_id'] == null ? undefined : json['credit_id'],
        'name': json['name'] == null ? undefined : json['name'],
        'gender': json['gender'] == null ? undefined : json['gender'],
        'profile_path': json['profile_path'] == null ? undefined : json['profile_path'],
    };
}

export function TvSeriesDetails200ResponseCreatedByInnerToJSON(value?: TvSeriesDetails200ResponseCreatedByInner | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'id': value['id'],
        'credit_id': value['credit_id'],
        'name': value['name'],
        'gender': value['gender'],
        'profile_path': value['profile_path'],
    };
}

