/* tslint:disable */
/* eslint-disable */
/**
 * TMDB API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { WatchProvidersMovieList200ResponseResultsInnerDisplayPriorities } from './WatchProvidersMovieList200ResponseResultsInnerDisplayPriorities';
import {
    WatchProvidersMovieList200ResponseResultsInnerDisplayPrioritiesFromJSON,
    WatchProvidersMovieList200ResponseResultsInnerDisplayPrioritiesFromJSONTyped,
    WatchProvidersMovieList200ResponseResultsInnerDisplayPrioritiesToJSON,
} from './WatchProvidersMovieList200ResponseResultsInnerDisplayPriorities';

/**
 * 
 * @export
 * @interface WatchProvidersMovieList200ResponseResultsInner
 */
export interface WatchProvidersMovieList200ResponseResultsInner {
    /**
     * 
     * @type {WatchProvidersMovieList200ResponseResultsInnerDisplayPriorities}
     * @memberof WatchProvidersMovieList200ResponseResultsInner
     */
    display_priorities?: WatchProvidersMovieList200ResponseResultsInnerDisplayPriorities;
    /**
     * 
     * @type {number}
     * @memberof WatchProvidersMovieList200ResponseResultsInner
     */
    display_priority?: number;
    /**
     * 
     * @type {string}
     * @memberof WatchProvidersMovieList200ResponseResultsInner
     */
    logo_path?: string;
    /**
     * 
     * @type {string}
     * @memberof WatchProvidersMovieList200ResponseResultsInner
     */
    provider_name?: string;
    /**
     * 
     * @type {number}
     * @memberof WatchProvidersMovieList200ResponseResultsInner
     */
    provider_id?: number;
}

/**
 * Check if a given object implements the WatchProvidersMovieList200ResponseResultsInner interface.
 */
export function instanceOfWatchProvidersMovieList200ResponseResultsInner(value: object): value is WatchProvidersMovieList200ResponseResultsInner {
    return true;
}

export function WatchProvidersMovieList200ResponseResultsInnerFromJSON(json: any): WatchProvidersMovieList200ResponseResultsInner {
    return WatchProvidersMovieList200ResponseResultsInnerFromJSONTyped(json, false);
}

export function WatchProvidersMovieList200ResponseResultsInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): WatchProvidersMovieList200ResponseResultsInner {
    if (json == null) {
        return json;
    }
    return {
        
        'display_priorities': json['display_priorities'] == null ? undefined : WatchProvidersMovieList200ResponseResultsInnerDisplayPrioritiesFromJSON(json['display_priorities']),
        'display_priority': json['display_priority'] == null ? undefined : json['display_priority'],
        'logo_path': json['logo_path'] == null ? undefined : json['logo_path'],
        'provider_name': json['provider_name'] == null ? undefined : json['provider_name'],
        'provider_id': json['provider_id'] == null ? undefined : json['provider_id'],
    };
}

export function WatchProvidersMovieList200ResponseResultsInnerToJSON(value?: WatchProvidersMovieList200ResponseResultsInner | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'display_priorities': WatchProvidersMovieList200ResponseResultsInnerDisplayPrioritiesToJSON(value['display_priorities']),
        'display_priority': value['display_priority'],
        'logo_path': value['logo_path'],
        'provider_name': value['provider_name'],
        'provider_id': value['provider_id'],
    };
}

